import type { ArticleMeta } from "./index"

export const meta: ArticleMeta = {
  slug: "10-period-facts",
  title: "10 Period Facts Every Woman Needs to Know",
  description: "From the '28-day myth' to why your period is a vital sign — here are 10 things about menstruation that most women were never taught but absolutely need to know.",
  category: "Cycle Basics",
  publishedAt: "2024-01-01",
  readingTime: 8,
  section: "Cycle Basics & Education",
}

export const faqs = [
  { q: "What counts as a normal period?", a: "A normal period lasts between 3 and 7 days and involves roughly 30–60 ml of total fluid. Blood color can range from bright red to deep cranberry, and flow should move freely rather than in large clots. Your cycle (day 1 of one period to day 1 of the next) should fall between 24 and 38 days in length, though it is normal for your own cycle to vary by a few days from month to month. What matters most is understanding your personal baseline — and recognizing when something has changed." },
  { q: "Does everyone ovulate on day 14?", a: "No. Day 14 ovulation is a statistical artifact tied to the assumption of a perfect 28-day cycle — which most women do not have. Ovulation timing varies considerably from person to person and from cycle to cycle. In a healthy cycle, ovulation can occur anywhere between days 12 and 21, depending on the length of your follicular phase. The only reliable ways to confirm ovulation are basal body temperature tracking, cervical mucus observation, and LH testing via ovulation predictor kits — not counting days on a calendar." },
  { q: "What is period blood actually made of?", a: "Menstrual fluid is a mix of blood, sloughed-off endometrial (uterine lining) tissue, cervical and vaginal secretions, immune cells, prostaglandins, and growth factors. The uterine lining that sheds was built over the entire preceding cycle under the influence of estrogen and progesterone — so the character of your flow (color, consistency, volume) gives you real information about your hormonal health that cycle. Very dark, clotted, or scanty flow often points to hormonal imbalances worth investigating." },
  { q: "Is cramping during your period normal?", a: "Some mild to moderate cramping in the first one to two days of a period is a normal physiological response — prostaglandins trigger uterine contractions to expel the lining, and that produces sensation. What is not normal is pain that disrupts your daily functioning, requires significant medication to get through, causes vomiting or fainting, or worsens with every cycle. That level of pain is a symptom — most often pointing toward endometriosis, adenomyosis, fibroids, or significant hormonal imbalance — and it deserves a proper medical evaluation, not a prescription for ibuprofen and reassurance that \"it's just your period.\"" },
  { q: "What does it mean that the period is a \"vital sign\"?", a: "In 2015, the American College of Obstetricians and Gynecologists formally stated that the menstrual cycle should be treated as a vital sign — just like blood pressure or heart rate — because it reflects the functioning of multiple interconnected body systems: the hypothalamus, pituitary, adrenal glands, thyroid, and ovaries. A regular ovulatory cycle signals that all of these systems are communicating properly. When cycles become irregular, very heavy, very light, or disappear altogether, it is a signal that something has gone wrong systemically — not just reproductively." },
  { q: "What does hormonal birth control actually do to your natural cycle?", a: "Hormonal birth control suppresses ovulation and overrides your body's natural hormone production with synthetic hormones. It does not balance your hormones, give your ovaries a rest, or reset your cycle. The monthly bleed that occurs during the pill's hormone-free interval is withdrawal bleeding — not a true menstrual period — and it tells you nothing about your underlying hormonal health. When you stop hormonal birth control, whatever was driving your original symptoms before you started is typically still present. For some women, it takes several months for natural ovulation to resume." },
  { q: "How do I start tracking my cycle effectively?", a: "Start with the basics: record the first day of each period and the day it ends, and note your symptoms — cramping, mood shifts, energy levels, breast tenderness, and spotting — throughout the month. To confirm ovulation, track your basal body temperature (BBT) each morning before getting out of bed, and observe your cervical mucus, which becomes clear and stretchy like raw egg white in the days leading up to ovulation. After three to six months of consistent tracking, you will have a clear picture of your personal cycle patterns and a useful record to bring to any healthcare appointments." },
]

const html = `
<p>If your menstrual education consisted of a brief, awkward health class and whatever you pieced together from tampon commercials, you are not alone. For most women, the gap between what we were taught about our cycles and what we actually need to know is enormous. That gap costs us — in years of unnecessary suffering, in dismissed symptoms, in conditions that go undiagnosed for a decade.</p>
<p>These 10 facts are not trivia. They are the foundation for understanding your body, advocating for yourself with your doctor, and finally making sense of what your cycle has been trying to tell you all along.</p>
<h2>1. The "28-day cycle" is a myth</h2>
<p>The idea that every woman has a 28-day cycle with ovulation landing precisely on day 14 is one of the most persistent — and most harmful — pieces of misinformation in women's health. A healthy menstrual cycle can range from <strong>24 to 38 days</strong>, and it is completely normal for your own cycle length to shift by several days from one month to the next.</p>
<p>Where did the myth come from? A few places. The lunar cycle runs about 29.5 days. The rhythm method, developed in the early 1900s, was built on the assumption of a uniform 28-day pattern. And the birth control pill — with its neat packaging of 28 pills designed to produce clockwork monthly bleeding — has been shaping cultural expectations about cycle length for decades. That monthly bleed on the pill is not even a real period; it is withdrawal bleeding triggered by the hormone-free days, a distinction that matters more than most people realize.</p>
<p>In reality, <a href="/articles/what-is-normal-menstrual-cycle-period">what counts as a normal menstrual cycle</a> depends entirely on your own body's patterns — not a number that was convenient for calendar math.</p>
<h2>2. Your period is your fifth vital sign</h2>
<p>Blood pressure, heart rate, temperature, respiratory rate — these are the four vital signs every doctor checks at every appointment. In 2015, the American College of Obstetricians and Gynecologists (ACOG) formally declared that the menstrual cycle should be treated as a fifth vital sign. The Society for Menstrual Cycle Research had been making this argument since 2005.</p>
<p>The reasoning is straightforward: your cycle is a readout of your hormonal, metabolic, and overall health status. A regular ovulatory cycle signals that your hypothalamus, pituitary gland, adrenals, thyroid, and ovaries are all communicating properly. When your cycle becomes irregular, unusually heavy, unusually light, or disappears altogether, your body is not being dramatic — it is flagging that something has gone wrong somewhere in that system.</p>
<p>ACOG's report specifically noted that "identification of abnormal menstrual patterns in adolescence may improve early identification of potential health concerns for adulthood." This means a teenager with wildly irregular cycles is not just going through a phase — she may be showing early signs of a condition that will worsen without attention.</p>
<h2>3. Period blood is not just blood</h2>
<p>Menstrual fluid is a surprisingly complex mix. Yes, it contains blood — but it also contains sloughed-off endometrial tissue, cervical and vaginal fluids, immune cells, prostaglandins, and growth factors. The uterine lining that sheds during your period was built over the course of your entire cycle under the influence of estrogen (which grows and thickens the lining) and progesterone (which matures and stabilizes it in preparation for a potential pregnancy).</p>
<p>This composition matters because the color, consistency, and volume of your menstrual fluid tell you something real about your hormonal health. Healthy period blood flows freely — think the consistency of good maple syrup — and ranges in color from bright ruby red to deep cranberry. Blood that is consistently dark brown or nearly black, very clotted, pasty, or watery is giving you information worth paying attention to. Clots larger than a quarter appearing regularly often point to estrogen dominance, progesterone deficiency, or insufficient blood flow to the pelvis.</p>
<p>The amount you bleed matters too. A normal period involves roughly 30–60 ml of total fluid loss — equivalent to about 6–10 regular tampons or pads per cycle. Consistently bleeding through protection every hour, passing large clots, or feeling dizzy and exhausted when your period arrives are signs of <a href="/articles/heavy-periods">heavy periods</a> that deserve medical evaluation.</p>
<h2>4. Period pain is common — but it is not normal</h2>
<p>This one is worth saying slowly: the fact that millions of women experience debilitating cramps does not mean cramps are biologically designed to be debilitating. Pain that disrupts your daily life, requires more than two standard ibuprofen to manage, sends you to bed, or causes nausea and vomiting is a symptom — not an inevitable feature of having a uterus.</p>
<p>Some degree of uterine cramping during the first day or two of a period is a normal part of the lining shedding process, driven by prostaglandins that trigger muscle contractions. But severe, ongoing, or progressively worsening pain is often a sign of an underlying condition — <a href="/articles/cause-of-painful-periods">the most common causes of painful periods</a> include endometriosis, adenomyosis, uterine fibroids, a malpositioned uterus, and significant progesterone deficiency or estrogen dominance.</p>
<p>The average time from first symptoms to diagnosis of endometriosis is still 3.5 to 12 years. That delay is in part because so many women are told their pain is normal. It is not. Pain that interferes with your life is information, and it deserves a proper investigation.</p>
<h2>5. Ovulation — not menstruation — is the main event</h2>
<p>Your period gets all the attention, but <strong>ovulation is the biological centerpiece of the menstrual cycle</strong>. The bleed you experience at the end of each cycle is a downstream result of what happened — or didn't happen — at ovulation. If there is no ovulation, there is still sometimes a bleed (called anovulatory bleeding), but it is not a true period, and the hormonal environment that produces it is very different.</p>
<p>Ovulation is how your body produces the majority of its progesterone, via the corpus luteum — the temporary gland that forms from the follicle after the egg is released. Progesterone supports sleep quality, bone density, mood regulation, and cardiovascular health. Estrogen, which rises in the lead-up to ovulation, supports brain function, skin, vaginal health, and more. These are not "reproductive" hormones in a narrow sense; they are system-wide hormones that your entire body depends on throughout your reproductive years.</p>
<p>This is why <a href="/articles/how-ovulation-works-and-why-its-so-important">understanding how ovulation works</a> is so important — and why a regular period is not the same as a healthy cycle. You can menstruate without ovulating. You cannot ovulate without experiencing real systemic benefits.</p>
<div class="article-cta-box">
<h3>Not sure what your cycle is telling you?</h3>
<p>The free Hormone Health Assessment asks about your cycle, energy, mood, and symptoms to give you a personalized picture of where your hormones may be out of balance — in about five minutes.</p>
<a class="btn btn-terra" href="https://fixyourperiod.app/quiz" target="_blank">Take the Free Assessment →</a>
</div>
<h2>6. Your cycle changes across your reproductive years</h2>
<p>The cycle you have at 16 is not the cycle you will have at 28, and neither looks like what you will experience at 38 or in perimenopause. Understanding that variation is normal — and that the changes at each stage deserve attention — can save years of confusion.</p>
<p>In the teenage years, cycles are often irregular as the hypothalamic-pituitary-ovarian axis matures. Anovulatory cycles (where no egg is released) are common in the first year or two after the first period. But persistent irregularity, very heavy bleeding, or severe pain during adolescence should not be dismissed as "just puberty." It can be an early marker of PCOS, endometriosis, or thyroid dysfunction.</p>
<p>Through the 20s and into the 30s, cycles tend to stabilize — though stress, nutrition, overexercise, and hormonal contraceptive use can all disrupt them significantly. In the late 30s, the follicular phase (the time from day 1 of bleeding until ovulation) can begin to shorten as the ovarian reserve changes. By perimenopause, cycles may become longer, shorter, or wildly unpredictable as ovulation becomes less consistent. Each of these transitions is worth tracking.</p>
<h2>7. Conventional period products often contain chemicals worth avoiding</h2>
<p>Most tampons and conventional pads are made from bleached cotton or synthetic rayon, and may contain synthetic fragrances, dioxins (a byproduct of the chlorine bleaching process), pesticide residues, and other compounds. The vaginal mucosa is highly absorptive tissue, which means anything in a tampon has a relatively direct route into the bloodstream — more direct than substances applied to the skin.</p>
<p>The good news is that better options are widely available and have improved dramatically in recent years. Organic cotton tampons and pads are now mainstream. Menstrual cups eliminate the issue of fiber exposure entirely. And <a href="/articles/period-underwear">period underwear</a> has evolved to offer genuinely effective, washable, toxin-free protection that works for many flow levels.</p>
<p>If you are dealing with conditions like endometriosis or other hormone-sensitive conditions, reducing your chemical exposure wherever possible — including in period products you use for several days every month — is a reasonable and achievable step.</p>
<h2>8. Hormonal birth control does not "reset" your hormones or give your ovaries a rest</h2>
<p>This is probably the most widespread myth about hormonal contraception, and it causes real harm. Hormonal birth control — the pill, patch, ring, hormonal IUD, implant, or injection — works by suppressing ovulation and overriding your body's natural hormone production. It does not balance your hormones; it replaces them with synthetic versions.</p>
<p>When you stop hormonal birth control, your body does not emerge refreshed with a clean hormonal slate. Whatever was driving irregular cycles, painful periods, or hormonal symptoms before you started the pill is typically still there — and in some cases may have progressed, because the pill was suppressing symptoms rather than addressing their cause. For some women, it takes months for natural ovulation to resume after stopping hormonal contraceptives.</p>
<p>Additionally, the monthly bleed that occurs during the pill's hormone-free interval is not a true menstrual period. It is withdrawal bleeding — a response to the drop in synthetic hormones — and it tells you nothing meaningful about your underlying hormonal health. There are <a href="/articles/5-things-must-know-hormonal-birth-control">important things to understand about hormonal birth control</a> before making decisions about starting or stopping it.</p>
<h2>9. Missing or irregular periods are your body's first distress signal</h2>
<p>When your period becomes irregular, significantly shorter, significantly longer, or disappears entirely — and pregnancy, perimenopause, and breastfeeding are not the explanation — your body is telling you that ovulation has been disrupted. And as we have established, disrupted ovulation is not just a reproductive issue. It is a systemic health signal.</p>
<p>The list of conditions that can disrupt ovulation is long: PCOS, hypothalamic amenorrhea (triggered by chronic undereating, overexercise, or severe psychological stress), thyroid disorders (both hypo and hyper), elevated prolactin, adrenal dysfunction, and primary ovarian insufficiency, among others. Research has linked chronically irregular cycles to a higher risk of cardiovascular disease, type 2 diabetes, ovarian cancer, and even premature mortality.</p>
<p>A <a href="/articles/period-late">late or missing period</a> is not something to shrug off or explain away with "I've just been stressed." Stress is a legitimate cause of cycle disruption — and it absolutely warrants investigation and action. The question is always: what is creating this level of stress, and how is it impacting the rest of your hormonal system?</p>
<h2>10. Your cycle phases shape your energy, mood, sleep, and cognition</h2>
<p>Your hormones do not operate at a flat, steady level throughout the month. They move through a predictable arc across the <a href="/articles/four-phases-of-your-menstrual-cycle">four phases of the menstrual cycle</a> — menstruation, the follicular phase, ovulation, and the luteal phase — and those fluctuations have measurable effects on your brain and body.</p>
<p>In the follicular phase, rising estrogen supports focus, sociability, verbal fluency, and higher pain tolerance. Around ovulation, estrogen peaks and many women notice elevated energy, confidence, and libido. In the luteal phase, progesterone rises and the nervous system begins to shift toward a more inward, rest-oriented state. Toward the end of the luteal phase, as both hormones drop, PMS symptoms can emerge — and when the underlying hormonal environment is off, they can become severe.</p>
<p>None of this means your productivity or wellbeing should be at the mercy of your hormones. It means that when you understand the rhythms, you can plan around them strategically — scheduling demanding cognitive work and social events when your energy supports it, protecting rest during the phases when your body is asking for it. This is not "cycle syncing" as a wellness trend; it is simply working with your biology rather than against it.</p>
<h2>What to do with this information</h2>
<p>Knowledge about your cycle is only useful if you act on it. Start by tracking your cycle — not just the date your period starts, but also ovulation signs (basal body temperature and cervical mucus are the most reliable), your energy levels, mood, sleep quality, and any symptoms that recur at predictable points in the month. Three to six months of this data will show you patterns that are almost impossible to see otherwise.</p>
<p>If what you find raises questions, bring it to a practitioner who takes menstrual health seriously. A regular cycle, ovulation confirmed by tracking, manageable symptoms, and a period that arrives without drama are the benchmarks. If you are not there yet, that gap is something worth closing — not accepting.</p>
`

export default function ArticleBody() {
  // eslint-disable-next-line react/no-danger
  return <div dangerouslySetInnerHTML={{ __html: html }} />
}
