import type { ArticleMeta } from "./index"

export const meta: ArticleMeta = {
  slug: "7-surprising-reasons-women-lose-their-hair",
  title: "7 Surprising Reasons Women Lose Their Hair",
  description: "Hair loss in women is almost always hormonal. Here are 7 root causes — from thyroid to ferritin to DHT — and what you can actually do about each one.",
  category: "Hormonal Health",
  publishedAt: "2024-01-01",
  readingTime: 9,
  section: "Lifestyle, Tools & Health",
}

export const faqs = [
  { q: "What lab should I ask for to check my iron — and what number am I looking for?", a: "Ask specifically for a serum ferritin test — not just a complete blood count or serum iron panel. Ferritin measures your iron storage protein, which is what hair follicles draw on for growth. The conventional \"normal\" range starts as low as 12 ng/mL, but research on hair loss consistently points to ferritin below 70 ng/mL as a threshold associated with shedding. Many women are told their iron is fine with a ferritin of 18 or 25 — numbers that are genuinely too low for hair health even if they pass a standard screening." },
  { q: "What's the difference between a normal TSH and an optimal TSH for hair?", a: "Conventional labs typically flag TSH as abnormal only above 4.5–5.0 mIU/L, depending on the lab. From a functional medicine standpoint, optimal TSH for symptom-free thyroid function — including healthy hair — is between 0.5 and 2.0 mIU/L. A TSH of 3.5 or 4.0 is technically \"within range\" but may be associated with enough subclinical hypothyroidism to affect hair follicles and other tissues. More importantly, TSH alone doesn't capture problems with T4-to-T3 conversion or thyroid hormone binding — which is why a full panel including free T4, free T3, and antibodies is far more informative than TSH by itself." },
  { q: "How long does post-pill hair loss typically last?", a: "Post-pill telogen effluvium usually begins two to four months after stopping hormonal birth control and peaks around months three to four. For most women, shedding slows noticeably by month five or six and resolves within six to nine months total as the body re-establishes its own ovulatory hormone cycle. If significant shedding continues beyond six months after stopping the pill, it's worth investigating other causes — particularly ferritin, thyroid function, and zinc — as the pill can deplete several nutrients that independently affect hair growth." },
  { q: "Does PCOS cause hair loss the same way male pattern baldness does?", a: "The mechanism is similar but not identical. In both cases, the androgen DHT binds to receptors in scalp follicles and triggers follicular miniaturization — follicles shrink progressively with each growth cycle, producing thinner, shorter hairs until growth stops. In women with PCOS, the driver is typically elevated insulin amplifying ovarian testosterone production, which then converts to DHT. The pattern in women is typically diffuse thinning at the crown and widening of the part, rather than the receding hairline seen in men, though some women do experience temporal recession. Addressing the insulin resistance underlying androgen excess is the most effective long-term strategy." },
  { q: "Should I take biotin for hair growth?", a: "Biotin supplementation will only meaningfully help if you have an actual biotin deficiency — which is uncommon in women eating a varied diet. Most of the dramatic \"biotin before and after\" marketing is not backed by clinical evidence in biotin-sufficient people. The more important nutrients for hair follicle function are zinc, iron (ferritin), vitamin D, and adequate dietary protein — deficiencies in any of these are far more common and have stronger evidence behind them. One important caution: high-dose biotin (5,000–10,000 mcg) can falsely skew thyroid lab results, so always pause biotin supplementation for at least a week before getting thyroid labs drawn." },
  { q: "When should I see a dermatologist about hair loss?", a: "See a dermatologist if you notice patchy hair loss (bald spots rather than diffuse thinning), scalp inflammation, scaling, or itching — these patterns can indicate conditions like alopecia areata or scalp psoriasis that require specific diagnosis and treatment. Also see a dermatologist if you've addressed the most common hormonal and nutritional root causes (ferritin, thyroid, androgens, vitamin D) and shedding continues at a significant level beyond nine to twelve months. A dermatologist can perform a scalp biopsy if needed and assess whether follicle miniaturization has progressed to a stage where topical or procedural interventions are warranted." },
  { q: "How long will it take to see hair regrowth once I address the root cause?", a: "This is the hardest part of hair recovery: it is slow. The hair growth cycle means that even after the underlying cause is corrected, you won't see new growth emerging for two to three months at minimum — that's how long it takes for a follicle to move from the resting phase back into active growth and produce a visible new hair. Full recovery of density typically takes six to twelve months after the root cause is resolved, and in some cases longer. Consistency matters more than speed here — stable labs, sustained nutritional support, and stress management over time produce the best results. Take monthly photos of your part and hairline to track progress, as the day-to-day changes are too subtle to notice without comparison." },
]

const html = `
<p>If you've noticed more hair in the shower drain, thinning at your temples, or a ponytail that feels noticeably thinner than it used to, you're not imagining it — and you're not alone. Hair loss in women is far more common than most people realize, and yet it remains one of the most under-investigated hormonal complaints in conventional medicine.</p>
<p>Here's what's important to understand: hair follicles are exquisitely sensitive to hormonal signals. The hair growth cycle — with its phases of active growth (anagen), transition (catagen), and resting (telogen) — is regulated by a web of hormones, nutrients, and stress signals. When any part of that web is disrupted, the follicles are often the first to show it.</p>
<p>Below are seven of the most common root causes of hair loss in women, along with the mechanisms behind each and specific steps you can take to start investigating.</p>
<h2>1. Thyroid Dysfunction</h2>
<figure class="article-image">
  <img src="https://res.cloudinary.com/dgmg40akd/image/upload/w_760,f_auto,q_auto/nj-articles-original/7-surprising-reasons-women-lose-their-hair/img-01" alt="What Causes Hair Loss In Women?" width="760" height="760" loading="lazy" />
  <figcaption class="article-image-caption">Hair loss in women often has hormonal root causes</figcaption>
</figure>

<p>The thyroid is one of the most powerful regulators of the hair growth cycle. Both <strong>hypothyroidism</strong> (underactive thyroid) and <strong>hyperthyroidism</strong> (overactive thyroid) can cause diffuse shedding across the entire scalp — the kind where you don't notice a bald patch so much as an overall thinning that creeps up slowly.</p>
<p>Thyroid hormones — particularly <strong>free T3</strong>, the active form — directly influence the anagen (growth) phase of the hair follicle. When thyroid hormone levels are low, follicles spend more time in the resting phase and less time actively growing. Over time, the result is fewer hairs on your head. Hyperthyroidism can also trigger shedding because the follicle cycle is pushed too fast, burning through the growth phase before hair can fully develop.</p>
<p>The most important thing to know here: <strong>a normal TSH does not rule out a thyroid problem.</strong> The conventional TSH range runs as wide as 0.45–5.0 mIU/L depending on the lab, but functional medicine practitioners work with an optimal range of 0.5–2.0 mIU/L. It's entirely possible to have a TSH of 3.8 — technically "normal" — and still have enough thyroid underfunction to affect your hair follicles. And TSH alone doesn't tell you how well T4 is being converted to the active T3 form in the liver, gut, and peripheral tissues.</p>
<p><strong>What to look for:</strong> Hair that is dry, coarse, or breaks easily alongside shedding. Outer third of the eyebrows thinning. Cold hands and feet, fatigue, constipation, low mood. Read more in the article on <a href="/articles/how-hyperthyroidism-affects-your-period">how thyroid dysfunction affects your hormonal health</a>.</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Ask your doctor for a <em>full thyroid panel</em>: TSH, free T4, free T3, and thyroid antibodies (TPO and TGAB). Don't accept a TSH-only result if you have symptoms.</li>
<li>Support thyroid conversion by addressing gut health and chronic stress — both of which impair the conversion of T4 to active T3 in peripheral tissues.</li>
</ul>
<h2>2. Low Ferritin (Iron Storage)</h2>
<p>This is the most commonly missed cause of hair loss in women — not because doctors aren't testing iron, but because they're testing the wrong marker. <strong>Serum iron and hemoglobin can look perfectly normal while your ferritin — the body's iron storage protein — is depleted.</strong> Hair follicles need ferritin to produce hair; when stores run low, the body prioritizes vital organs and the follicles get cut off from supply.</p>
<p>Research suggests that <strong>ferritin below 70 ng/mL</strong> is associated with hair loss in women, even when levels fall within the conventional "normal" range (which often starts as low as 12–15 ng/mL). Many women are told their iron is fine when their ferritin is sitting at 18 or 22 — levels that leave hair follicles starved.</p>
<p>The most common reasons women deplete ferritin: heavy periods (even periods that feel "normal" but are on the heavier side), low dietary iron, poor iron absorption from gut inflammation, and vegetarian or plant-heavy diets where non-heme iron absorption is limited. Vitamin C significantly enhances iron absorption, so pairing iron-rich foods with a vitamin C source makes a real difference.</p>
<p><strong>What to look for:</strong> Diffuse shedding, fatigue, shortness of breath on exertion, pale inner eyelids, cold hands and feet. Hair that snaps or breaks easily is a common sign of low ferritin even before classic anemia sets in.</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Ask specifically for a <em>serum ferritin</em> test and aim for a result of at least 70 ng/mL for hair health — not just "within range."</li>
<li>If ferritin is low, investigate the cause first: address heavy bleeding, gut absorption, and copper-zinc balance before supplementing. If supplementation is needed, iron bisglycinate is gentler on the digestive system than ferrous sulfate.</li>
</ul>
<h2>3. Post-Pill Hair Loss</h2>
<p>Coming off hormonal birth control is one of the most common — and least discussed — triggers for significant hair shedding in women. What's happening is a form of <strong>telogen effluvium</strong>: a mass shift of hair follicles from the active growth phase into the resting phase, triggered by a sudden change in the hormonal environment.</p>
<p>While on the pill, synthetic estrogen and progestin maintain an artificially stable hormonal environment. The pill suppresses ovulation, which means there's no real estrogen fluctuation, no progesterone production from the corpus luteum, and no natural hormonal rhythm. When the pill is stopped, the body suddenly has to restart its own hormonal production — and during the adjustment period (which can last two to six months), estrogen levels can dip significantly before the ovarian cycle regains its footing. This estrogen withdrawal signals follicles to shed.</p>
<p>Additionally, some synthetic progestins used in hormonal contraceptives have androgenic activity — meaning they can bind to androgen receptors and promote the kind of follicle miniaturization associated with DHT-driven hair loss. Women who are genetically sensitive to androgens may notice this effect especially on the hairline and crown.</p>
<p><strong>What to look for:</strong> Shedding that begins two to four months after stopping the pill, peaking around month three to four and gradually improving. The timing is the key clue.</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Support your body's natural hormone production post-pill with adequate protein, zinc, and B vitamins, which are often depleted by long-term pill use. Read more about <a href="/articles/come-birth-control-pill-right-way">coming off the birth control pill the right way</a>.</li>
<li>Be patient — post-pill telogen effluvium is self-resolving in most cases once ovulation resumes. If shedding continues beyond six months, investigate other root causes on this list.</li>
</ul>
<div class="article-cta-box">
<h3>Not sure what's driving your hair loss?</h3>
<p>Hair shedding is often just one of several signals your hormones are sending. The free Hormone Health Assessment maps your symptoms to possible hormonal patterns — and takes less than five minutes.</p>
<a class="btn btn-terra" href="https://fixyourperiod.app/quiz" target="_blank">Take the Free Assessment →</a>
</div>
<h2>4. Postpartum Hair Loss</h2>
<p>Losing alarming handfuls of hair two to four months after giving birth is so common it has a name — <strong>postpartum telogen effluvium</strong> — and yet many new mothers are blindsided by it and assume something is seriously wrong.</p>
<p>During pregnancy, elevated estrogen levels keep hair follicles locked in the anagen (growth) phase far longer than usual. This is why many women enjoy the thickest hair of their lives while pregnant. After delivery, estrogen levels plummet rapidly — one of the sharpest hormonal drops the body experiences — and all those follicles that were held in growth mode simultaneously shift into the resting phase. Two to four months later (the normal length of the telogen phase), they all shed at once.</p>
<p>Postpartum hair loss is biologically normal and typically resolves within six to twelve months as hormone levels stabilize and the hair cycle resets. However, if shedding continues beyond twelve months postpartum, or is accompanied by other symptoms, it's worth checking thyroid function, ferritin, and vitamin D — all of which are commonly depleted during pregnancy and the postpartum period and can extend or worsen hair loss independently.</p>
<p><strong>What to look for:</strong> Diffuse shedding starting around two to four months postpartum, especially at the temples and hairline. This is typically a volume loss rather than patchy loss.</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Continue taking your prenatal vitamin through the postpartum period to maintain B vitamins, zinc, and iron stores that support the follicle cycle.</li>
<li>If shedding persists past twelve months postpartum, request labs for ferritin, TSH, free T3, free T4, and vitamin D.</li>
</ul>
<h2>5. DHT and Androgen Excess</h2>
<p><strong>Dihydrotestosterone (DHT)</strong> is a potent androgen derived from testosterone via an enzyme called 5-alpha reductase. While DHT plays important roles in the body, when levels are elevated relative to other hormones, it can bind to receptors in hair follicles on the scalp and trigger a process called <strong>follicular miniaturization</strong> — the follicle gradually shrinks, producing thinner, shorter hairs with each growth cycle until it eventually stops producing hair altogether.</p>
<p>In women, androgen excess is most commonly associated with <strong>PCOS</strong>, where elevated insulin amplifies LH signaling in the ovaries, driving excess production of testosterone and its conversion to DHT. But androgen excess can also occur in women without a PCOS diagnosis — through HPA axis dysregulation (chronic stress driving adrenal androgen production), low sex hormone binding globulin (SHBG), or even certain synthetic progestins in hormonal birth control that mimic androgenic activity.</p>
<p>The pattern of hair loss from DHT is typically androgenic alopecia: thinning at the crown and widening of the part, sometimes with hairline recession at the temples. It progresses slowly and may not be immediately obvious.</p>
<p><strong>What to look for:</strong> Crown thinning or a widening part. Acne along the jawline and chin. Excess facial or body hair. Irregular cycles longer than 35 days. Learn more about <a href="/articles/pcos-high-prolactin-levels-primary-ovarian-insufficiency-common">PCOS and androgen excess</a>.</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Ask for labs including free and total testosterone, DHEA-S, and SHBG. SHBG that is low allows more free testosterone to be converted to DHT.</li>
<li>Address insulin resistance if present — it is one of the most powerful drivers of ovarian androgen production. Reducing refined carbohydrates, supporting blood sugar balance, and improving sleep all help lower insulin and subsequently DHT.</li>
</ul>
<h2>6. Nutritional Deficiencies</h2>
<p>Hair follicles are among the most metabolically active cells in the body — they are dividing rapidly and require a consistent, generous supply of micronutrients to do so. When the diet is inadequate, or when absorption is impaired (as it often is with chronic stress, gut dysfunction, or hormonal contraceptive use), several specific deficiencies can directly impair hair growth.</p>
<p><strong>Zinc</strong> is essential for follicle development, ovulation, and thyroid hormone production — a triple role that makes deficiency particularly impactful for hair. Zinc deficiency presents as diffuse shedding, and it is more common in women who eat a plant-heavy diet because the phytic acid in legumes and grains inhibits zinc absorption. The recommended supplemental dose when deficiency is present is 15–30 mg of zinc picolinate or bisglycinate taken after food.</p>
<p><strong>Biotin</strong> has been heavily marketed for hair growth, but actual biotin deficiency is rare in women who eat a varied diet. The bigger issue is that biotin depends on adequate zinc and other B vitamins to function effectively. If you are supplementing biotin, be aware that high-dose biotin supplementation can interfere with thyroid lab results — always pause it for at least a week before thyroid testing.</p>
<p><strong>Vitamin D</strong> has receptors in hair follicles and plays a role in initiating the anagen phase of the hair cycle. Low vitamin D is associated with alopecia areata as well as diffuse shedding. The challenge is that true vitamin D sufficiency for hair health may require levels of 50–80 ng/mL — higher than the conventional minimum of 30 ng/mL. Get tested before supplementing; if levels are low, 5,000 IU of vitamin D3 paired with vitamin K2 daily is a common protocol. Read more about <a href="/articles/vitamin-d-the-period-vitamin">vitamin D and your hormonal health</a>.</p>
<p><strong>Protein</strong> is the structural building block of hair itself — hair is made of keratin, a protein. Chronic undereating or very low-protein diets create a physiological stress signal that pushes follicles into telogen. Aim for at least 0.7–1 gram of protein per pound of body weight daily, prioritizing complete protein sources.</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Test serum zinc, vitamin D, and ferritin before supplementing. Guessing at deficiencies can lead to imbalances — copper and zinc compete for absorption, and excess of one can deplete the other.</li>
<li>Focus on dietary sources first: oysters, beef, and pumpkin seeds for zinc; egg yolks and fatty fish for vitamin D; quality animal protein for keratin-building amino acids. Supplements fill gaps, but they work best on a foundation of nutrient-dense eating.</li>
</ul>
<h2>7. Chronic Stress and HPA Axis Dysregulation</h2>
<p>Cortisol is often called the body's stress hormone, but it is also a powerful regulator of hair follicle biology. Chronically elevated cortisol — the result of ongoing psychological stress, poor sleep, blood sugar swings, gut infections, over-exercise, or any combination of modern life stressors — disrupts the hair growth cycle in several interconnected ways.</p>
<p>First, elevated cortisol directly suppresses the anagen phase by triggering premature entry into catagen and telogen. Second, cortisol impairs the conversion of T4 to active T3 by suppressing the deiodinase enzyme — which means chronic stress quietly degrades thyroid function and compounds its effects on hair follicles. Third, prolonged HPA axis dysregulation reduces DHEA production, shifts the adrenals toward excess androgen output, and can lower progesterone — all of which further disturb the hormonal environment that follicles depend on.</p>
<p>There is also a direct signaling pathway: cortisol receptors are present in hair follicle cells, and sustained cortisol exposure has been shown in research to inhibit follicle stem cell activation — the very step that triggers a new anagen (growth) phase. This is why people often notice increased shedding during or after a period of intense stress, sometimes with a delay of two to four months after the stressor (matching the telogen effluvium timeline).</p>
<p>The frustrating reality is that because the endocrine system operates as a hierarchy — cortisol and insulin at the top, with sex hormones and thyroid below — no amount of targeted hair supplements will fully compensate for a nervous system that is chronically in overdrive. Supporting the stress response is the foundational work. Read more about <a href="/articles/how-stress-affects-your-menstrual-cycle">how chronic stress affects your hormones</a>, and explore the role of <a href="/articles/the-many-benefits-of-<a href="https://amzn.to/35yjnY9" target="_blank" rel="noopener noreferrer" class="article-link">magnesium</a>-for-your-health-cycle">magnesium</a> — which is rapidly depleted by stress and plays a key role in HPA axis regulation.</p>
<p><strong>What to look for:</strong> Diffuse shedding that began or worsened during or after a high-stress period. Accompanying symptoms of HPA dysregulation: difficulty falling or staying asleep, afternoon energy crashes, anxiety, sugar cravings, and feeling "wired but tired."</p>
<p><strong>Action steps:</strong></p>
<ul>
<li>Prioritize sleep as a non-negotiable — it is the single most impactful intervention for normalizing cortisol patterns. Aim for consistent sleep and wake times and minimize light exposure after dark.</li>
<li>Supplement with magnesium glycinate (300–400 mg before bed) — magnesium is depleted by stress and is essential for HPA axis regulation, thyroid conversion, and hundreds of biochemical reactions that support hair follicle health.</li>
</ul>
<h2>Putting It Together</h2>
<p>Hair loss in women rarely has a single cause. More often, it reflects an overlap — low ferritin plus subclinical hypothyroidism, or chronic stress driving both androgen excess and nutrient depletion. The key is to investigate systematically rather than defaulting to biotin supplements or expensive topicals that address symptoms while the root cause continues unaddressed.</p>
<p>The starting point is always labs: ferritin (not just iron), a full thyroid panel, free testosterone and SHBG, vitamin D, and zinc. From there, the pattern becomes clearer, and targeted support becomes possible. Your hair is one of the most visible readouts of what's happening inside your hormonal system — and it's worth listening to.</p>
`

export default function ArticleBody() {
  // eslint-disable-next-line react/no-danger
  return <div dangerouslySetInnerHTML={{ __html: html }} />
}
