/**
 * Article CTA copy — generated by scripts/generate-article-ctas.mjs
 * Each entry maps a slug to {headline, body} for the quiz CTA at the bottom
 * of the article page. null means use the generic fallback.
 */

export interface ArticleCta {
  headline: string
  body: string
}

export const articleCtas: Record<string, ArticleCta | null> = {
  "periods-in-perimenopause": {
    headline: "Get clarity on your changing perimenopausal periods.",
    body: "Whether your cycles are suddenly shorter, longer, or completely unpredictable, the Hormone Health Assessment can help. Take the free quiz to get a personalized protocol for navigating this transition with fewer surprises.",
  },
  "periods-101-instagram-series": {
    headline: "Not sure if your period is actually normal?",
    body: "Take the free Hormone Health Assessment to find out what your cycle is really telling you. You'll get a personalized protocol based on your unique symptoms and patterns.",
  },
  "what-is-normal-menstrual-cycle-period": {
    headline: "Not sure if your cycle is actually normal?",
    body: "Take the free Hormone Health Assessment to find out what your cycle length, flow, and timing reveal about your hormonal health — and get a personalized protocol to address what's off.",
  },
  "how-long-should-your-period-be": {
    headline: "Not sure if your period length is normal?",
    body: "Whether your period is unusually short or dragging on too long, it could signal a hormonal imbalance. Take this free Hormone Health Assessment to get a personalized protocol based on your unique cycle patterns.",
  },
  "four-phases-of-your-menstrual-cycle": {
    headline: "Understand how your hormones shift through each cycle phase.",
    body: "Take the free Hormone Health Assessment to discover how well your body is moving through menstrual, follicular, ovulatory, and luteal phases — and get a personalized protocol to support your cycle from start to finish.",
  },
  "how-ovulation-works-and-why-its-so-important": null,
  "the-menstrual-life-cycle": {
    headline: "Understand what your cycle needs at every stage.",
    body: "Whether you're navigating your first periods or noticing shifts as you age, your hormones have different needs over time. Take this free quiz to get a personalized protocol based on where you are right now.",
  },
  "10-period-facts": null,
  "period-shame": null,
  "endometriosis": {
    headline: "Get personalized support for managing endometriosis naturally.",
    body: "Take the free Hormone Health Assessment to uncover what's driving your symptoms — from painful periods to inflammation — and receive a customized protocol to help you find relief.",
  },
  "adenomyosis": {
    headline: "Could adenomyosis be behind your heavy, painful periods?",
    body: "If you're struggling with symptoms that could point to adenomyosis, understanding your full hormonal picture is the first step. Take this free Hormone Health Assessment to get a personalized protocol for managing heavy bleeding and pain.",
  },
  "heavy-periods": {
    headline: "Find out what's behind your heavy periods.",
    body: "Take this free Hormone Health Assessment to uncover the root causes of your heavy bleeding — whether it's estrogen dominance, nutrient deficiencies, or something else — and get a personalized protocol to bring your cycle back into balance.",
  },
  "cause-of-painful-periods": {
    headline: "Find out what's behind your painful periods.",
    body: "Take the free Hormone Health Assessment to uncover what's driving your cramps, inflammation, or cycle imbalances — and get a personalized protocol to help you find real, lasting relief.",
  },
  "menstrual-migraines": {
    headline: "Find the root cause of your menstrual migraines.",
    body: "Estrogen fluctuations are just one piece of the puzzle. Take the free Hormone Health Assessment to uncover what's driving your monthly headaches and get a personalized protocol to help prevent them.",
  },
  "pcos-high-prolactin-levels-primary-ovarian-insufficiency-common": {
    headline: "Get clarity on what's really going on with your hormones.",
    body: "Whether you're dealing with irregular cycles, missing periods, or unexplained symptoms, the Hormone Health Assessment can help. Take the free quiz to get a personalized protocol based on your unique hormonal picture.",
  },
  "how-to-prevent-ovarian-cysts": {
    headline: "Ovarian cysts often point to a deeper hormonal issue.",
    body: "Take the free Hormone Health Assessment to uncover what's driving your cyst-prone cycles. You'll get a personalized protocol addressing the root imbalances—whether it's estrogen dominance, irregular ovulation, or inflammation.",
  },
  "histamine-intolerance-and-your-period": {
    headline: "Could histamine be driving your worst PMS symptoms?",
    body: "The connection between histamine and estrogen might explain your cycle-related headaches, hives, or intense cramps. Take the free Hormone Health Assessment to get a personalized protocol that addresses your specific symptoms.",
  },
  "post-menstrual-syndrome-pms-after-period": {
    headline: "Find out what's behind your post-menstrual symptoms.",
    body: "If you're dealing with anxiety, fatigue, or low mood after your period ends, your estrogen levels may need support. Take this free quiz to get a personalized protocol for your cycle.",
  },
  "how-to-take-your-life-back-from-pmdd": {
    headline: "Get real answers for your PMDD symptoms.",
    body: "Take the free Hormone Health Assessment to uncover what's driving your luteal phase mood shifts, energy crashes, and emotional overwhelm — and get a personalized protocol to start feeling like yourself again.",
  },
  "mthfr-what-is-it-and-why-you-should-know-for-the-sake-of-your-fertility": {
    headline: "Wondering how MTHFR is affecting your hormones?",
    body: "Gene variants like MTHFR can impact everything from fertility to energy levels. Take the free Hormone Health Assessment to get a personalized protocol that supports your body's unique methylation and detox needs.",
  },
  "how-hyperthyroidism-affects-your-period": {
    headline: "Find out if your thyroid is affecting your cycle.",
    body: "If you're dealing with light, irregular, or missing periods, your thyroid could be playing a role. Take the free Hormone Health Assessment to get a personalized protocol for supporting your hormones and your cycle.",
  },
  "how-your-thyroid-can-cause-period-and-fertility-problems": {
    headline: "Could your thyroid be behind your period problems?",
    body: "Thyroid dysfunction can quietly disrupt your cycle and fertility. Take the free Hormone Health Assessment to uncover what's driving your symptoms and get a personalized protocol to support your thyroid and hormonal balance.",
  },
  "help-why-am-i-spotting": {
    headline: "Find out what your spotting is trying to tell you.",
    body: "Whether it's mid-cycle or right before your period, spotting points to an underlying hormonal pattern. Take the free Hormone Health Assessment to uncover what's driving it and get a personalized protocol to address the root cause.",
  },
  "period-start-stop-start-again": {
    headline: "Find out what's behind your stop-start period.",
    body: "That frustrating pattern of starting, stopping, and starting again points to a hormonal imbalance. Take the free Hormone Health Assessment to uncover what's disrupting your flow and get a personalized protocol to restore consistency.",
  },
  "low-progesterone-why-it-happens-and-what-you-can-do-about-it": {
    headline: "Low progesterone affects everything from PMS to fertility.",
    body: "Take the free Hormone Health Assessment to uncover what's behind your luteal phase symptoms, cycle irregularities, or trouble conceiving — and get a personalized protocol to support healthy progesterone levels.",
  },
  "lengthen-your-luteal-phase": {
    headline: "A short luteal phase doesn't have to derail your cycle.",
    body: "Take the free Hormone Health Assessment to uncover what's behind your luteal phase issues and get a personalized protocol to support progesterone production, improve cycle length, and boost your fertility.",
  },
  "when-to-test-progesterone-levels": {
    headline: "Not sure if low progesterone is your issue?",
    body: "Testing is key, but knowing what to test starts with understanding your symptoms. Take this free Hormone Health Assessment to uncover what's really going on and get a personalized protocol to support your levels.",
  },
  "progesterone-vs-progestin": {
    headline: "Not sure if your hormones need natural progesterone support?",
    body: "Take the free Hormone Health Assessment to uncover what's really driving your symptoms — whether it's low progesterone, estrogen dominance, or something else. You'll get a personalized protocol tailored to your unique hormonal picture.",
  },
  "the-real-reason-your-breasts-are-sore-before-your-period": {
    headline: "Find Out What's Behind Your Breast Tenderness",
    body: "Sore breasts before your period can point to estrogen dominance or low progesterone. Take the free Hormone Health Assessment to uncover what's driving your symptoms and get a personalized protocol for relief.",
  },
  "dim-sgs-i3c": {
    headline: "Not sure if estrogen metabolism is your issue?",
    body: "Before adding DIM or sulforaphane to your routine, find out what's actually driving your symptoms. Take the free Hormone Health Assessment to get a personalized protocol based on your unique hormonal patterns.",
  },
  "hormones-and-weight": {
    headline: "Find Out Which Hormones Are Driving Your Weight Struggles",
    body: "Weight gain tied to hormonal imbalance requires a targeted approach. Take the free Hormone Health Assessment to uncover what's disrupting your metabolism and get a personalized protocol to help break the cycle.",
  },
  "how-stress-affects-your-menstrual-cycle": {
    headline: "Find out how stress is disrupting your cycle.",
    body: "Chronic stress can throw off everything from ovulation to your period. Take the free Hormone Health Assessment to uncover how stress may be affecting your hormones and get a personalized protocol to restore balance.",
  },
  "the-cortisol-connection": {
    headline: "Is cortisol disrupting your hormonal balance?",
    body: "Chronic stress affects everything from your cycle to your thyroid. Take the free Hormone Health Assessment to uncover how stress may be impacting your hormones and get a personalized protocol to restore balance.",
  },
  "why-modern-women-need-to-rethink-stress": {
    headline: "Stress is quietly disrupting your hormones.",
    body: "Take the free Hormone Health Assessment to uncover how chronic stress may be affecting your cycle, energy, and mood — and get a personalized protocol to start restoring balance.",
  },
  "overlooked-sources-of-stress": {
    headline: "Hidden stressors could be sabotaging your hormones.",
    body: "From blood sugar crashes to screen time overload, stress shows up in surprising ways. Take the Hormone Health Assessment to uncover what's disrupting your balance and get a personalized protocol to support your stress response.",
  },
  "how-the-menstrual-cycle-affects-blood-sugar-and-insulin-regulation-in-the-body": {
    headline: "Blood sugar swings disrupting your cycle?",
    body: "Insulin resistance can silently drive irregular periods, intense cravings, and hormonal chaos. Take the free Hormone Health Assessment to uncover how blood sugar may be affecting your cycle and get a personalized protocol to stabilize it.",
  },
  "5-things-that-can-stop-ovulation-impair-fertility": {
    headline: "Find out what's blocking your ovulation.",
    body: "If you suspect something's interfering with your cycle and fertility, take the free Hormone Health Assessment. You'll get a personalized protocol addressing the specific factors that may be suppressing your ovulation.",
  },
  "is-your-period-playing": {
    headline: "Find Out What's Behind Your Unpredictable Cycle",
    body: "If your period keeps you guessing every month, the Hormone Health Assessment can help. Take this free quiz to uncover what's driving your irregular symptoms and get a personalized protocol to bring clarity back to your cycle.",
  },
  "5-things-must-know-hormonal-birth-control": {
    headline: "Wondering how birth control has affected your hormones?",
    body: "Whether you're currently on hormonal contraception or recently came off, nutrient depletion and hormonal shifts can show up in unexpected ways. Take the free Hormone Health Assessment to get a personalized protocol for rebalancing your body.",
  },
  "birthcontrolsideeffects": {
    headline: "Wondering how birth control is affecting your hormones?",
    body: "Whether you're considering going off the pill or managing current side effects, understanding your unique hormonal picture is the first step. Take the free Hormone Health Assessment to get a personalized protocol for rebalancing your body.",
  },
  "come-birth-control-pill-right-way": {
    headline: "Wondering what your hormones need post-pill?",
    body: "Coming off birth control is just the first step. Take this free Hormone Health Assessment to uncover what's really going on and get a personalized protocol to help you avoid the post-pill hormonal chaos.",
  },
  "birth-control-pill-weight-gain": {
    headline: "Wondering if the pill is affecting your weight?",
    body: "Hormonal shifts from birth control can impact metabolism, cravings, and how your body stores fat. Take the free Hormone Health Assessment to get a personalized protocol that addresses your unique symptoms.",
  },
  "the-pill-your-sex-drive-how-to-start-reclaiming-your-va-va-voom": {
    headline: "Low libido shouldn't be a side effect you just accept.",
    body: "If hormonal birth control has tanked your sex drive, your hormones need support. Take the free Hormone Health Assessment to get a personalized protocol for reclaiming your desire and rebalancing testosterone and SHBG.",
  },
  "how-to-start-using-natural-birth-control": {
    headline: "Ready to understand your cycle on a deeper level?",
    body: "Practicing FAM means knowing your body's signals inside and out. Take the free Hormone Health Assessment to get a personalized protocol that supports the healthy, predictable cycles natural birth control depends on.",
  },
  "how-does-the-mirena-iud-work-is-it-right-for-me": {
    headline: "Considering the Mirena IUD for heavy periods?",
    body: "Before choosing any hormonal intervention, understand what's driving your symptoms. Take the free Hormone Health Assessment to uncover the root causes of heavy bleeding and get a personalized protocol for your cycle.",
  },
  "copperiud": {
    headline: "Wondering if your IUD is affecting your hormones?",
    body: "Whether you're considering the copper IUD or already have one, understanding your unique hormonal balance matters. Take the free Hormone Health Assessment to get a personalized protocol for managing heavy periods and other symptoms.",
  },
  "vitamin-d-the-period-vitamin": {
    headline: "Is low vitamin D affecting your cycle?",
    body: "Painful periods, PCOS, and endometriosis are all linked to vitamin D status — but they rarely exist in isolation. Take this free Hormone Health Assessment to uncover what's driving your symptoms and get a personalized protocol.",
  },
  "how-to-test-your-vitamin-d-levels": {
    headline: "Find out what your vitamin D levels mean for your hormones.",
    body: "Low vitamin D can affect everything from your cycle to your mood. Take the free Hormone Health Assessment to get a personalized protocol that addresses nutrient gaps and the symptoms they cause.",
  },
  "the-many-benefits-of-magnesium-for-your-health-cycle": {
    headline: "Find out if magnesium is the missing piece for your cycle.",
    body: "Take the free Hormone Health Assessment to get a personalized protocol based on your unique symptoms — whether that's cramps, PMS, sleep issues, or anxiety. Your results will show exactly what your body needs.",
  },
  "vitamin-c-for-your-cycle": {
    headline: "Not sure if vitamin C is the missing piece for your cycle?",
    body: "Take the free Hormone Health Assessment to uncover what's driving your symptoms — whether it's low progesterone, adrenal stress, or poor iron absorption — and get a personalized protocol to bring your cycle back into balance.",
  },
  "vitex-hormones-fertility": {
    headline: "Not sure if vitex is right for your hormones?",
    body: "Low progesterone and luteal phase issues need a targeted approach. Take the free Hormone Health Assessment to get a personalized protocol based on your unique cycle patterns and symptoms.",
  },
  "cholesterol-great-hormones": {
    headline: "Is your diet giving your hormones what they need?",
    body: "Cholesterol and healthy fats are the building blocks of hormone production. Take the free Hormone Health Assessment to get a personalized protocol addressing your unique nutritional gaps and hormonal imbalances.",
  },
  "does-being-vegan-affect-your-period": {
    headline: "Wondering if your vegan diet is affecting your cycle?",
    body: "Nutrient gaps like B12, iron, and zinc can quietly disrupt your hormones. Take this free Hormone Health Assessment to get a personalized protocol that addresses your specific deficiencies and cycle symptoms.",
  },
  "is-gluten-bad": {
    headline: "Find out if inflammation is disrupting your hormones.",
    body: "If you're dealing with PCOS, endometriosis, or autoimmune-related symptoms, diet is just one piece of the puzzle. Take the free Hormone Health Assessment to get a personalized protocol for calming inflammation and rebalancing your cycle.",
  },
  "the-effect-of-coffee-on-your-hormones-and-menstrual-cycle": {
    headline: "Wondering if coffee is messing with your hormones?",
    body: "Your caffeine tolerance depends on your unique hormonal picture. Take the free Hormone Health Assessment to get a personalized protocol addressing your cortisol, estrogen balance, and energy levels.",
  },
  "dry-january-alcohol-free-resources": {
    headline: "Wondering how alcohol is affecting your cycle?",
    body: "Your drinking habits are just one piece of the puzzle. Take this free Hormone Health Assessment to uncover what's really driving your estrogen levels, liver function, and cycle symptoms — and get a personalized protocol to address it.",
  },
  "howyourperiodaffectsdigestivetract": {
    headline: "Tired of digestive chaos around your period?",
    body: "Bloating, diarrhea, and constipation don't have to derail your cycle every month. Take the free Hormone Health Assessment to get a personalized protocol that addresses the gut-hormone connection behind your symptoms.",
  },
  "antibiotics-effect-period": {
    headline: "Antibiotics threw off your cycle? Find your reset plan.",
    body: "Gut disruption can quietly affect your estrogen levels and period health. Take the free Hormone Health Assessment to get a personalized protocol for restoring balance — from digestion to cycle regularity.",
  },
  "livercleansehormones": {
    headline: "Find out what your liver needs for better hormone balance.",
    body: "If you're dealing with estrogen dominance symptoms like heavy periods, PMS, or stubborn weight gain, your liver may need support. Take the Hormone Health Assessment to get a personalized protocol for improving estrogen detoxification.",
  },
  "vaginal-microbiome-testing": {
    headline: "Your vaginal microbiome is just one piece of the puzzle.",
    body: "Imbalances in your vaginal flora often point to deeper hormonal issues. Take the free Hormone Health Assessment to get a personalized protocol addressing the root causes of infections, fertility challenges, and cycle irregularities.",
  },
  "chronic-utis-killing-sex-life": {
    headline: "Chronic UTIs often signal deeper hormonal imbalance.",
    body: "Recurrent infections can be tied to low estrogen, vaginal microbiome disruption, and gut health issues. Take this free Hormone Health Assessment to uncover what's driving your symptoms and get a personalized protocol to restore balance.",
  },
  "seed-cycling": {
    headline: "Find out if seed cycling belongs in your protocol.",
    body: "Seed cycling can support estrogen and progesterone balance—but it works best as part of a bigger picture. Take the free Hormone Health Assessment to get a personalized protocol based on your unique cycle symptoms.",
  },
  "my-favorite-tips-products-for-sleep-support": {
    headline: "Sleep struggles could be a sign of hormone imbalance.",
    body: "Poor sleep affects everything from cortisol to estrogen to progesterone. Take the free Hormone Health Assessment to uncover what's driving your restless nights and get a personalized protocol to help you finally sleep better.",
  },
  "emfs-effect-on-your-menstrual-cycle-and-fertility": {
    headline: "Could EMF exposure be disrupting your hormones?",
    body: "Environmental factors like EMFs can quietly impact your cycle and fertility. Take the free Hormone Health Assessment to uncover what's affecting your hormonal balance and get a personalized protocol to support your body.",
  },
  "connection-dental-health-hormones": {
    headline: "Could your oral health be affecting your hormones?",
    body: "Inflammation from dental issues can quietly disrupt your entire hormonal system. Take the free Hormone Health Assessment to get a personalized protocol that addresses the root causes of hormonal imbalance — including the ones you might not expect.",
  },
  "period-underwear": {
    headline: "Your period products are just one piece of the puzzle.",
    body: "Choosing safer underwear matters — but so does understanding what's driving your symptoms. Take the free Hormone Health Assessment to get a personalized protocol for your cycle, from flow issues to PMS and beyond.",
  },
  "use-drugstore-feminine-wipes": {
    headline: "Irritation and imbalance start with what you're using daily.",
    body: "If you're rethinking your feminine care routine, your hormones may need attention too. Take the free Hormone Health Assessment to get a personalized protocol for restoring balance from the inside out.",
  },
  "steam-vagina": {
    headline: "Curious what your vaginal health is really telling you?",
    body: "Before trying trendy treatments, get clarity on what's actually going on with your hormones. Take this free quiz to uncover the root causes behind symptoms like odor, dryness, or irritation—and get a personalized protocol.",
  },
  "mayan-abdominal-massage": {
    headline: "Curious if pelvic circulation is affecting your cycle?",
    body: "Abdominal massage is just one piece of the puzzle. Take the free Hormone Health Assessment to uncover what's driving your period pain, fertility challenges, or cycle irregularities—and get a personalized protocol to address it.",
  },
  "castor-oil": {
    headline: "Ready to support your liver and hormonal balance?",
    body: "Castor oil packs are just one piece of the puzzle. Take the free Hormone Health Assessment to get a personalized protocol addressing inflammation, detox pathways, and symptoms like painful periods or pelvic discomfort.",
  },
  "period-cycle-tracking-apps": {
    headline: "Track your cycle with purpose — not just guesswork.",
    body: "Knowing which app to use is just the first step. Take the free Hormone Health Assessment to uncover what your cycle patterns actually mean and get a personalized protocol to address irregular periods, PMS, or other hormonal imbalances.",
  },
  "my-favorite-fertility-tracking-devices": {
    headline: "Ready to decode what your cycle is telling you?",
    body: "Tracking your fertility is just the first step. Take the free Hormone Health Assessment to get a personalized protocol based on your unique cycle patterns, symptoms, and hormonal health goals.",
  },
  "7-surprising-reasons-women-lose-their-hair": {
    headline: "Find out what's really behind your hair loss.",
    body: "Thinning hair often signals deeper hormonal or nutritional imbalances. Take the free Hormone Health Assessment to uncover what's driving your symptoms and get a personalized protocol to address the root cause.",
  },
  "period-late": {
    headline: "Find out what's behind your late or missing period.",
    body: "Whether it's stress, undereating, or a hormonal imbalance, the Hormone Health Assessment will help you uncover the root cause and give you a personalized protocol to get your cycle back on track.",
  },
}
