import type { ArticleMeta } from "./index"

export const meta: ArticleMeta = {
  slug: "four-phases-of-your-menstrual-cycle",
  title: "The Four Phases of Your Menstrual Cycle",
  description: "Your menstrual cycle is far more than just your period. Learn what's happening hormonally in each of the four phases — menstrual, follicular, ovulatory, and luteal — and how to work with them.",
  category: "Cycle Basics",
  publishedAt: "2024-01-01",
  readingTime: 10,
  section: "Cycle Basics & Education",
}

export const faqs = [
  { q: "How long is a normal menstrual cycle?", a: "A normal cycle ranges from about 25 to 35 days. The variation between individuals comes almost entirely from differences in follicular phase length — not the luteal phase, which is relatively fixed for any given person at around 11 to 16 days. A cycle shorter than 21 days or longer than 35 days on a consistent basis is worth investigating. So is a cycle that is highly irregular month to month — a variation of more than 7 days between cycles can indicate irregular or absent ovulation." },
  { q: "Is it normal to feel different in different weeks of my cycle?", a: "Yes, completely. The hormonal fluctuations across your cycle directly affect brain chemistry, neurotransmitter activity, energy metabolism, immune function, and more. Many people feel most energized and social during the follicular and ovulatory phases, when estrogen and testosterone are higher. The luteal phase tends to bring more inward focus and lower physical energy. The menstrual phase is a natural reset. These differences are real and biological — not imaginary, not a weakness, and not something to suppress." },
  { q: "How do I know if I actually ovulated?", a: "Having a period does not confirm ovulation — you can have an anovulatory bleed (bleeding without ovulation) that looks very similar to a normal period. The most reliable at-home confirmation of ovulation combines two things: a sustained basal body temperature (BBT) rise of about 0.2–0.4°C for at least three days after a period of fertile cervical mucus, and a positive ovulation predictor kit (OPK) reading in the days before. A mid-luteal progesterone blood test — drawn about 7 days after suspected ovulation — is the most objective confirmation." },
  { q: "What does fertile cervical mucus look like, and when does it appear?", a: "Cervical fluid changes throughout the cycle in response to shifting estrogen and progesterone levels. Right after your period you may notice little to no fluid. As estrogen rises in the follicular phase, fluid becomes more noticeable — first creamy or lotiony, then progressively more wet and slippery. At peak fertility, just before ovulation, it becomes clear, very stretchy, and slick — often described as resembling raw egg white. This fertile-quality mucus can keep sperm viable for up to 5 days, which is why the fertile window starts before ovulation day. After ovulation, progesterone dries the fluid back down to sticky, tacky, or absent." },
  { q: "Why do I get PMS? Is it hormonal?", a: "Yes, PMS is fundamentally hormonal — but the cause is usually not excess progesterone, it is a relative imbalance between progesterone and estrogen in the luteal phase, compounded by what is happening in the brain. Progesterone normally metabolizes into a calming compound called allopregnanolone, which acts on GABA receptors. When progesterone is low — often because ovulation was weak or delayed, or because stress is blocking its effects — this calming action is reduced and anxiety, irritability, and poor sleep follow. Improving ovulation quality, reducing cortisol, supporting liver estrogen clearance, and ensuring adequate magnesium and B6 are usually the most effective starting points." },
  { q: "Can the birth control pill regulate my cycle?", a: "No — and this is one of the most important distinctions to understand. Hormonal birth control does not regulate your cycle, it replaces it. The synthetic hormones suppress your own hormone production entirely, preventing ovulation and eliminating the four natural phases. The monthly bleed that occurs during the placebo week is a withdrawal bleed caused by the drop in synthetic hormones — it is not a true period. If you were prescribed the pill to \"regulate\" irregular cycles, the underlying cause of those irregularities has not been addressed; it has been masked. When you stop the pill, the original issue will still be there." },
  { q: "What is the luteal phase and how long should it be?", a: "The luteal phase is the second half of your cycle — from ovulation to the day before your next period. It is governed by progesterone produced by the corpus luteum, the temporary endocrine gland that forms from the follicle that released your egg. A healthy luteal phase is generally 11 to 16 days, with 12 to 14 days being most common. A luteal phase shorter than 10 days is considered a deficiency and is associated with low progesterone, difficulty with implantation, and fertility challenges. For more detail on supporting luteal phase health, see the article on luteal phase support ." },
  { q: "Does cycle syncing actually work?", a: "The concept is grounded in real biology. Each phase of the cycle is characterized by a distinct hormonal profile that affects energy, recovery, cognition, and emotional experience in measurable ways. Aligning your exercise intensity, social commitments, nutrition, and rest with those natural rhythms is not magical thinking — it is working with your body's existing design rather than against it. Higher-intensity exercise and social output are genuinely better tolerated in the follicular and ovulatory phases when estrogen and testosterone are higher. Rest and inward focus in the late luteal and menstrual phases align with the body's natural hormonal slowdown. The specifics will differ for every person, so personal cycle tracking is the best guide." },
]

const html = `
<p>When most people think about their menstrual cycle, they think about their period — the bleeding part. But your period is just one event in a much larger, more intricate monthly rhythm. Your entire cycle, from the first day of bleeding to the day before your next period begins, is a dynamic hormonal sequence involving your brain, your ovaries, your uterus, and a cast of hormones that affect everything from your energy and cognition to your immune function and bone density.</p>
<p>Female bodies are cyclical by nature, producing varying quantities of estrogen, progesterone, testosterone, and other hormones at different points throughout the month. These fluctuations are not flaws or inconveniences — they are the operating system. Understanding them is one of the most powerful things you can do for your health. If you have ever felt like a completely different person from one week to the next, that is because hormonally, you practically are.</p>
<p>The menstrual cycle is divided into four phases. Two major ones — the <strong>follicular phase</strong> and the <strong>luteal phase</strong> — bookend the cycle. Nested within them are two events: <strong>menstruation</strong> at the start and <strong>ovulation</strong> at the midpoint. Each phase has its own hormonal signature, its own physical and emotional texture, and its own nutritional and lifestyle needs. Let's walk through all four.</p>
<h2>Phase 1: The Menstrual Phase (Days 1–5)</h2>
<figure class="article-image">
  <img src="https://res.cloudinary.com/dgmg40akd/image/upload/w_760,f_auto,q_auto/nj-articles-original/four-phases-of-your-menstrual-cycle/img-04" alt="MENSTRUATION PHASE" width="760" height="642" loading="lazy" />
  <figcaption class="article-image-caption">The menstrual phase marks the beginning of your cycle</figcaption>
</figure>

<div class="phase-label">Days 1–5 • Estrogen &amp; Progesterone at Their Lowest</div>
<h3>What is happening hormonally</h3>
<p>Day 1 of your cycle is the first day of full bleeding — not spotting, but actual flow. At this point, both estrogen and progesterone have dropped to their lowest levels of the entire cycle. It is this withdrawal of progesterone, specifically, that signals the uterine lining it is time to shed. The endometrium releases pro-inflammatory prostaglandins that trigger uterine contractions, which push the lining out. Menstruation is, at its core, an inflammatory process.</p>
<p>While the bleeding is happening, your brain is already setting the next cycle in motion. The hypothalamus has been secreting gonadotropin-releasing hormone (GnRH), which instructs the pituitary gland to release follicle-stimulating hormone (FSH). FSH travels to the ovaries and begins recruiting a small group of follicles — each one a tiny fluid-filled sac containing an egg — for potential development. So even as your body is shedding, it is already preparing for what comes next.</p>
<p>The average bleeding phase lasts 3 to 7 days. Your cervix sits low in the vaginal canal, is firm to the touch, and is slightly open to allow blood to pass.</p>
<h3>What is normal — and what is not</h3>
<p>Some cramping in the first day or two is common and is caused by prostaglandin-driven contractions. What is <em>not</em> normal: pain that stops your life, requires prescription medication, or radiates into your back and thighs. Severely painful periods — especially ones that worsen over time — can be a sign of endometriosis, adenomyosis, or very high prostaglandin production driven by inflammation and estrogen excess. For more on what healthy bleeding looks like, see <a href="/articles/how-long-should-your-period-be">how long your period should be</a> and the <a href="/articles/periods-101-instagram-series">periods 101 series</a>.</p>
<p>Heavy bleeding that soaks through a pad or tampon every hour for several hours, clots larger than a quarter, or bleeding that lasts more than 7 days are also signs worth investigating, not normalizing.</p>
<h3>What to eat and do</h3>
<p>This is a time for genuine rest. Your body is doing significant work, and your energy is naturally lower. Honor that rather than push through it. Nutritionally, focus on iron-rich foods to replenish what is lost through bleeding — red meat, dark leafy greens, lentils, and pumpkin seeds. Pair plant-based iron with vitamin C to improve absorption. Omega-3 fatty acids (found in fatty fish, walnuts, and flaxseed) are particularly helpful during menstruation because they support the production of anti-inflammatory prostaglandins, which counterbalance the cramping-inducing ones.</p>
<p>Gentle movement — walking, restorative yoga, stretching — tends to feel better than high-intensity exercise for most people during this phase. <a href="https://amzn.to/1S2XroX" target="_blank" rel="noopener noreferrer" class="article-link">Heat on the lower abdomen</a> can ease cramping by relaxing uterine muscles and improving blood flow.</p>
<h2>Phase 2: The Follicular Phase (Days 1–13)</h2>
<figure class="article-image">
  <img src="https://res.cloudinary.com/dgmg40akd/image/upload/w_760,f_auto,q_auto/nj-articles-original/four-phases-of-your-menstrual-cycle/img-05" alt="THE FOLLICULAR PHASE" width="760" height="451" loading="lazy" />
  <figcaption class="article-image-caption">Rising estrogen during the follicular phase brings renewed energy</figcaption>
</figure>

<div class="phase-label">Days 1–13 • FSH Rises, Estrogen Builds</div>
<h3>What is happening hormonally</h3>
<p>The follicular phase technically begins on day 1 alongside menstruation and continues until ovulation — so it overlaps with the bleeding phase for its first several days. Once menstruation ends, the follicular phase enters its more energizing second half.</p>
<p>FSH continues stimulating the recruited follicles, and by around days 5 to 7, one dominant follicle emerges from the group (the others will gradually break down). This dominant follicle becomes the star of the show. Inside it, specialized cells begin converting androgens into estradiol — the most potent form of estrogen. As the follicle grows, estradiol rises steadily, and this rising estrogen feeds back to the brain, signaling that follicle development is on track.</p>
<p>Rising estrogen also begins thickening the uterine lining, stimulates the cervix to start producing more fluid, and — crucially — shifts LH (luteinizing hormone) production upward in preparation for ovulation. By the time the follicular phase is wrapping up, estrogen is climbing toward its monthly peak.</p>
<p>It is worth noting: the length of <em>your</em> follicular phase is what determines the length of your overall cycle. A shorter follicular phase means a shorter cycle; a longer one means a longer cycle. Once you ovulate, the luteal phase that follows is relatively fixed in length — usually 11 to 16 days. This is why cycle length varies between women but the post-ovulatory phase is fairly predictable for any given person.</p>
<h3>Energy, mood, and cognition</h3>
<p>This is often the phase when people feel their best. Estrogen has a broadly positive effect on mood, energy, verbal fluency, and working memory. Serotonin sensitivity improves. Physical recovery from exercise is faster. Social energy is often higher. Many people notice they are more talkative, more creative, and more optimistic during the follicular phase — not by coincidence, but because of estrogen's direct effects on brain chemistry.</p>
<h3>Best activities for this phase</h3>
<p>The follicular phase is an ideal time to start new projects, schedule important conversations or presentations, take on challenging workouts, and make decisions that require fresh thinking. High-intensity interval training, strength training, and cardio are generally well-tolerated and beneficial here. Your body is primed for output.</p>
<p>Nutritionally, lighter foods tend to feel good during this phase — plenty of vegetables, lean proteins, and complex carbohydrates. Fermented foods support the estrogen-metabolizing gut bacteria that help keep estrogen balanced as it rises.</p>
<h2>Phase 3: The Ovulatory Phase (Days 12–16)</h2>
<div class="phase-label">Days 12–16 • LH Surge, Peak Estrogen &amp; Testosterone</div>
<h3>What is happening hormonally</h3>
<p>Ovulation is the main event of the entire menstrual cycle — not menstruation. Everything in the follicular phase has been building toward this moment. When estradiol from the dominant follicle reaches a threshold high enough to be sustained for roughly 50 hours, it triggers a dramatic surge of LH from the pituitary gland. This LH surge — which typically occurs between midnight and 8 a.m. — starts about 35 to 44 hours before the egg is actually released.</p>
<p>The LH surge causes a cascade: it induces the granulosa cells inside the follicle to begin producing progesterone, which (along with prostaglandins and enzymes) weakens the follicle wall until it ruptures, releasing the mature egg into the peritoneal cavity. From there, the fimbriae — finger-like projections at the end of the fallopian tube — sweep the egg into the tube, where it travels toward the uterus. The egg is viable for 12 to 24 hours. The whole ovulatory event, from LH surge to egg release, spans roughly 24 to 48 hours.</p>
<p>Testosterone also peaks during this window, contributing to increased libido, assertiveness, and physical drive. This hormonal peak — estrogen and testosterone together — is responsible for the characteristic energy surge many people notice at ovulation.</p>
<h3>Cervical mucus and signs of ovulation</h3>
<p>As ovulation approaches, cervical fluid transforms into what is called fertile-quality mucus: clear, slippery, and stretchy — like raw egg white. This fluid nourishes and protects sperm, guides them toward the egg, and can keep sperm viable in the reproductive tract for up to 5 days. This is why the fertile window actually spans several days before ovulation, not just ovulation day itself.</p>
<p>Other signs you may notice around ovulation: a slight rise in resting body temperature (which becomes more apparent in the day or two after ovulation), a softer and higher-positioned cervix, and sometimes a brief twinge or ache on one side of the lower abdomen known as mittelschmerz. Some people also notice increased social energy and a subtle but real improvement in physical appearance — skin tends to be at its clearest, and facial symmetry is slightly more pronounced around ovulation, per research.</p>
<p>To learn more about the factors that can interfere with the ovulatory process, see the article on <a href="/articles/5-things-that-can-stop-ovulation-impair-fertility">5 things that can stop ovulation</a>.</p>
<h3>A note on the pill's "withdrawal bleed"</h3>
<p>This is important: if you are on hormonal birth control — the combined pill in particular — you are not experiencing any of these phases. Hormonal contraceptives work by suppressing the HPO axis (the brain-ovary communication system), preventing FSH and LH from being released, and therefore preventing ovulation entirely. The "period" you get on the pill is not a real period. It is a withdrawal bleed caused by the drop in synthetic hormones during the placebo pill week. The lining that sheds is not a hormonally built endometrium in the same way — it is thinner and produced differently. There is no ovulatory phase, no corpus luteum, no natural progesterone rise, and no four-phase cycle. Everything is flattened to a synthetic hormonal baseline.</p>
<h2>Phase 4: The Luteal Phase (Days 15–28)</h2>
<div class="phase-label">Days 15–28 • Progesterone Rises, Corpus Luteum Forms</div>
<h3>What is happening hormonally</h3>
<p>Once the egg is released, the empty follicle transforms into a temporary endocrine gland called the <strong>corpus luteum</strong> — Latin for "yellow body," named for the yellow carotenoid pigment it contains. This remarkable structure, which your body assembles in under 24 hours, begins pumping out progesterone in significant quantities. Progesterone is the dominant hormone of the luteal phase, and it is responsible for preparing the uterine lining for potential implantation, raising basal body temperature, and shifting cervical fluid from wet and stretchy to thick and tacky.</p>
<p>Estrogen makes one more appearance mid-luteal phase, rising briefly in a last-ditch effort to further support the endometrium. This can sometimes produce a small amount of creamy cervical fluid — not fertile-quality, but noticeable.</p>
<p>The corpus luteum has a natural lifespan of about 11 to 16 days. If no pregnancy occurs, it breaks down, progesterone and estrogen both drop sharply, and this withdrawal triggers menstruation — beginning the cycle again. If the egg is fertilized, the embryo releases hCG (human chorionic gonadotropin), which signals the corpus luteum to keep producing progesterone until the placenta can take over, around 7 to 10 weeks after conception.</p>
<p>A luteal phase shorter than 10 days is considered a luteal phase deficiency and is associated with insufficient progesterone, difficulty sustaining implantation, and infertility. For strategies to support a healthy luteal phase, see the article on <a href="/articles/lengthen-your-luteal-phase">lengthening your luteal phase</a>.</p>
<h3>PMS and the progesterone connection</h3>
<p>PMS — mood changes, bloating, breast tenderness, irritability, fatigue — typically occurs in the week before your period, when progesterone is declining. The root of most PMS is not excess progesterone but rather a progesterone-to-estrogen imbalance: either progesterone is too low to begin with (often because ovulation was weak or didn't occur), or estrogen remains relatively higher than it should be in the late luteal phase.</p>
<p>This imbalance affects brain chemistry directly. Progesterone metabolizes into a compound called allopregnanolone, which acts on GABA receptors in the brain — the same receptors targeted by anti-anxiety medications. When progesterone is low, allopregnanolone is low, and the calming, mood-stabilizing effect it normally provides disappears. That explains the anxiety, irritability, and sleep disruption that often characterize late-luteal PMS.</p>
<h3>Energy and intentional slowing</h3>
<p>Energy in the luteal phase is generally lower than in the follicular and ovulatory phases — and this is not a malfunction. Progesterone is a calming, heat-generating hormone. Your metabolic rate is slightly elevated, you may feel warmer, and your body is doing significant cellular work preparing for either pregnancy or menstruation. This is a phase designed for consolidation, not expansion.</p>
<p>Many people find the early luteal phase (days 15 to 21) still productive and focused, while the late luteal phase (days 22 onward) calls for more rest, inward attention, and lighter scheduling. Honoring this rhythm, rather than fighting it, tends to dramatically reduce the intensity of PMS symptoms over time.</p>
<h3>Supporting the luteal phase</h3>
<p>Magnesium is particularly important during this phase. It supports progesterone production, helps regulate the HPA stress axis, reduces inflammation, and has been shown in research to significantly reduce PMS symptoms including mood swings, bloating, and craving for refined carbohydrates. A therapeutic dose is typically 300 to 400 mg of magnesium glycinate or bisglycinate taken in the second half of the cycle.</p>
<p>Stress management is also critical here. Cortisol competes with progesterone for the same receptor sites, effectively blocking progesterone's action even when levels are adequate. A chronically high stress load in the luteal phase will worsen every PMS symptom — not because progesterone is lower, but because cortisol is getting in the way. Prioritizing sleep, reducing high-intensity exercise, and protecting your capacity for genuine rest are among the most effective interventions available.</p>
<p>Vitamin B6 supports the liver's ability to clear excess estrogen and is directly involved in progesterone production. Zinc supports the corpus luteum's progesterone output. Chasteberry (vitex agnus-castus) has been used traditionally — and studied clinically — to support the luteal phase and reduce PMS, primarily by supporting LH activity and therefore corpus luteum function.</p>
<h2>How Cycle Awareness Can Change How You Plan Your Life</h2>
<p>Once you understand the four phases, your cycle stops being something that happens <em>to</em> you and becomes something you can work <em>with</em>. The follicular and ovulatory phases are natural times for high output — networking, presentations, launching projects, intense workouts, bold decisions. The luteal phase supports analytical thinking, editing, consolidating, and wrapping up what was started. The menstrual phase is a reset — a time for reflection, rest, and identifying what is and isn't working.</p>
<p>Cycle syncing — the practice of aligning your work, social commitments, exercise, and nutrition with your cycle's natural phases — is not a productivity hack. It is simply recognizing that your body has built-in rhythms, and that working with them rather than against them reduces the friction and exhaustion that comes from trying to maintain a flat, constant level of output every single day of the month.</p>
<p>Tracking your cycle — even just noting which day you are on, what your energy feels like, and whether you observe ovulation signs — creates a feedback loop that makes everything clearer over time. You start to recognize patterns, anticipate how you will feel, and distinguish between symptoms that need attention and fluctuations that are normal and cyclical.</p>
<h2>The Pill's Effect: Removing the Phases Entirely</h2>
<p>It bears repeating: hormonal birth control does not regulate your cycle. It replaces it. The synthetic hormones in the combined pill, patch, and hormonal ring suppress the HPO axis, preventing the brain from sending the FSH and LH signals that drive follicle development and ovulation. Without ovulation, there is no corpus luteum, no natural progesterone, no four-phase rhythm.</p>
<p>What users experience instead is a steady, flat dose of synthetic hormones — progestin and synthetic estrogen — with no natural fluctuation. The four phases, with all their hormonal benefits to mood, energy, cognition, libido, and metabolic function, do not exist. The withdrawal bleed that happens during the placebo week is not a period in the physiological sense. It does not indicate that ovulation occurred, that a uterine lining was built under natural hormonal influence, or that the body went through its normal cycle.</p>
<p>This is not a judgment of anyone's contraceptive choices — it is simply important information. If you have been on the pill for years and feel like your mood, libido, or energy have been flat or suppressed, understanding what the pill does at a hormonal level is the starting point for making informed decisions about your options.</p>
<div class="article-cta-box">
<h3>Find out what your cycle is telling you</h3>
<p>Take the free Hormone Health Assessment — 30 questions about your cycle, symptoms, and lifestyle — and receive a personalized action plan built for your body.</p>
<a class="btn btn-terra" href="https://fixyourperiod.app/quiz" target="_blank">Take the Free Assessment →</a>
</div>
`

export default function ArticleBody() {
  // eslint-disable-next-line react/no-danger
  return <div dangerouslySetInnerHTML={{ __html: html }} />
}
