import type { ArticleMeta } from "./index"

export const meta: ArticleMeta = {
  slug: "how-your-thyroid-can-cause-period-and-fertility-problems",
  title: "How Your Thyroid Affects Your Period & Fertility",
  description: "Thyroid dysfunction is one of the most overlooked causes of period problems and infertility. Here's how hypothyroidism and Hashimoto's affect your cycle — and what to do about it.",
  category: "Thyroid",
  publishedAt: "2024-01-01",
  readingTime: 10,
  section: "Conditions & Symptoms",
}

export const faqs = [
  { q: "What is a \"normal\" TSH level, and why does it matter which range you use?", a: "The conventional TSH reference range used by most labs and doctors spans approximately 0.45–5.0 mIU/L. This range was derived from statistical averages across a broad population that included many already-ill individuals. Functional medicine practitioners use a narrower optimal range of 0.5–2.0 mIU/L, based on populations of healthy people who feel well. The difference matters enormously in practice: a TSH of 3.8 or 4.2 would be considered \"normal\" by conventional standards, but from a functional perspective it signals the pituitary is working hard to compensate for a struggling thyroid — and the woman may have clear hypothyroid symptoms that go unaddressed because her doctor considers the result unremarkable." },
  { q: "Can hypothyroidism cause symptoms that look like PCOS?", a: "Yes, and this is one of the most commonly missed diagnostic overlaps. Hypothyroidism can cause irregular cycles, anovulation, elevated androgens (through reduced SHBG and altered ovarian hormone production), weight gain, and insulin resistance — all symptoms that overlap significantly with polycystic ovary syndrome. Before accepting a PCOS diagnosis, a full thyroid panel including antibodies should always be done. In some cases, treating an underlying thyroid condition resolves what looked like PCOS. In others, both conditions are present simultaneously, and both need to be addressed." },
  { q: "Does Hashimoto's mean I need to go gluten-free?", a: "The evidence strongly suggests yes, particularly if you have confirmed Hashimoto's or elevated TPO/TgAb antibodies. The protein gliadin in gluten closely resembles transglutaminase, an enzyme abundant in thyroid tissue. The immune system's antibodies against gliadin can cross-react with thyroid tissue through a process called molecular mimicry — especially in the context of intestinal permeability. Multiple studies have shown that a strict gluten-free diet reduces thyroid antibody levels and can improve thyroid function over time. You do not need a celiac diagnosis for this to be relevant; non-celiac gluten sensitivity can drive the same immune response." },
  { q: "What labs should I ask my doctor to run for a complete thyroid picture?", a: "At minimum, ask for: TSH, free T4, free T3, reverse T3, TPO antibodies, and thyroglobulin antibodies (TgAb). Total T4 and total T3 can also be useful, as can thyroid binding globulin (TBG) if estrogen dominance or hormonal birth control is a factor. If hyperthyroidism or Graves' disease is suspected, thyroid stimulating immunoglobulin (TSI) and thyrotropin receptor antibodies (TRAb) should be added. Many conventional doctors will initially push back on ordering a full panel — you may need to be persistent, or seek out a functional medicine or naturopathic physician who routinely runs comprehensive thyroid testing." },
  { q: "How long does it take to see period improvements once thyroid function is supported?", a: "It depends on how long the thyroid has been struggling and how significant the dysfunction is. With foundational dietary and lifestyle changes — removing gluten, stabilizing blood sugar, addressing nutrient deficiencies, and reducing toxic load — many women begin to notice improvements in energy and cycle regularity within two to three months. Full normalization of heavy periods, luteal phase length, and progesterone levels may take longer, particularly if iron stores are depleted and need to be rebuilt. If thyroid medication is needed, it typically takes four to six weeks for levels to stabilize after a dosage change, and menstrual changes often follow within one to two cycles after that." },
  { q: "Can thyroid issues cause infertility?", a: "Absolutely. Thyroid dysfunction affects fertility through multiple pathways simultaneously: it disrupts ovulation (via elevated prolactin and impaired follicle development), reduces progesterone production, lowers basal body temperature (which can prevent embryo implantation and increase early miscarriage risk), and creates an overall energy deficit that the body prioritizes over reproduction. Subclinical hypothyroidism — where TSH is only mildly elevated — is strongly associated with recurrent miscarriage and difficulty conceiving, which is why many reproductive endocrinologists now treat thyroid levels more aggressively in women who are trying to get pregnant. If you are trying to conceive and experiencing difficulty, a comprehensive thyroid panel should be a first-line investigation, not an afterthought." },
  { q: "What role does selenium play in thyroid health, and should I supplement it?", a: "Selenium is one of the most important nutrients for thyroid function. The thyroid contains the highest concentration of selenium of any organ in the body, and selenium is essential for three key functions: converting T4 into active T3 (via the enzyme deiodinase), protecting thyroid tissue from oxidative damage during hormone production, and supporting glutathione production, which helps regulate immune activity and reduce thyroid antibody levels. Clinical trials have shown that selenium supplementation (200 mcg per day of selenomethionine) significantly reduces TPO antibody levels in Hashimoto's patients. Food sources include a few Brazil nuts daily, seafood, and organ meats. If supplementing, stay at or below 200 mcg per day — selenium has a narrow therapeutic window and excess supplementation can be harmful." },
]

const html = `
<p>If you've been struggling with <a href="/articles/heavy-periods">heavy periods</a>, irregular cycles, low progesterone, or unexplained infertility — and your doctor keeps telling you everything looks "normal" — your thyroid may be the missing piece of the puzzle.</p>
<p>Thyroid dysfunction is one of the most common yet consistently underdiagnosed causes of period problems in women. And the reason it gets missed so often comes down to inadequate testing, overly wide "normal" reference ranges, and a medical culture that treats the thyroid in isolation rather than as part of a deeply connected hormonal ecosystem.</p>
<p>This guide covers everything you need to understand about the thyroid-cycle connection: how hypothyroidism slows and disrupts your cycle, how hyperthyroidism can make it disappear, why Hashimoto's is almost always overlooked, what testing you actually need, and what you can do to support your thyroid naturally.</p>
<h2>The Thyroid-Reproductive Hormone Connection</h2>


<p>Think of your body's hormonal system as three overlapping command centers that all share the same headquarters — your hypothalamus and pituitary gland. These are the <strong>hypothalamic-pituitary-adrenal (HPA) axis</strong>, the <strong>hypothalamic-pituitary-thyroid (HPT) axis</strong>, and the <strong>hypothalamic-pituitary-ovarian (HPO) axis</strong>.</p>
<p>Because all three axes run through the same two master glands, they are in constant communication. When one gets disrupted, the ripple effects move through all three. Chronic stress that overloads the HPA axis will suppress the HPT axis. A sluggish thyroid will dampen the HPO axis. Your period and your thyroid are not separate systems — they are parts of one interconnected whole.</p>
<p>The thyroid gland itself produces two key hormones: <strong>T4 (thyroxine)</strong> and <strong>T3 (triiodothyronine)</strong>. T4 is the more abundant form — about 80% of thyroid output — but T3 is the biologically active form that cells actually use, with roughly four times the potency of T4. The body converts T4 to T3 primarily in the liver and gut, which means that even if your thyroid is producing adequate T4, poor gut or liver health can still leave you functionally low in thyroid hormone.</p>
<p>Every cell in your body has receptor sites for thyroid hormone — including the cells in your ovaries, uterus, and endometrium. Your ovaries need thyroid hormone to grow healthy follicles, produce estrogen and progesterone, and support ovulation. When thyroid hormone is insufficient, your entire reproductive system feels it.</p>
<h2>How Hypothyroidism Disrupts Your Period</h2>
<p>An underactive thyroid — hypothyroidism — creates a cascade of effects that touches nearly every aspect of your menstrual cycle. Here are the most significant ones:</p>
<h3>Elevated prolactin and disrupted ovulation</h3>
<p>Hypothyroidism disrupts pituitary hormone production, often causing <strong>hyperprolactinemia</strong> — elevated levels of the hormone prolactin. High prolactin interferes with the pulsatile release of GnRH (gonadotropin-releasing hormone) from the hypothalamus, which in turn blunts the LH surge needed to trigger ovulation. The result: cycles where ovulation is irregular, delayed, or doesn't happen at all — what's called <strong>anovulatory cycles</strong>.</p>
<p>Anovulatory cycles mean the corpus luteum never forms, progesterone never rises, and the uterine lining continues to build under the influence of unopposed estrogen before eventually shedding. This is a primary driver of <a href="/articles/heavy-periods">heavy, prolonged bleeding</a> and can contribute to <a href="/articles/low-progesterone-why-it-happens-and-what-you-can-do-about-it">low progesterone</a> and the classic luteal phase defect pattern.</p>
<h3>Direct effects on the ovarian follicles</h3>
<p>Thyroid hormone receptors are found directly on ovarian tissue. T3 is needed at multiple stages of follicle development: it supports the proliferation of granulosa cells, helps suppress excess androgen production by theca cells, supports the conversion of androgens to estrogen, and stimulates progesterone production from the corpus luteum.</p>
<p>When thyroid hormone is chronically low, follicle development is impaired, ovulation sputters, and progesterone production declines. This creates a cycle of <strong>estrogen dominance and progesterone deficiency</strong> — the underlying driver of a wide range of PMS symptoms, heavy periods, and fertility challenges.</p>
<h3>Impaired estrogen metabolism and altered SHBG</h3>
<p>Hypothyroidism slows the liver's ability to metabolize and clear estrogen from the body, allowing estrogen levels to rise. At the same time, it lowers <strong>sex hormone binding globulin (SHBG)</strong>, a protein that normally binds and transports estrogen and testosterone in the blood. Lower SHBG means higher levels of free, unbound estrogen and testosterone circulating in the body — contributing to heavier periods, shorter cycles, and symptoms of androgen excess.</p>
<h3>Reduced blood clotting factors</h3>
<p>Hypothyroidism decreases the production of clotting factors that help regulate menstrual bleeding. This is a direct physiological reason why women with low thyroid function so often experience <a href="/articles/heavy-periods">heavy, prolonged periods</a>. Over time, heavy periods deplete iron stores and can lead to iron deficiency anemia — which then further impairs thyroid function, since iron is required for thyroid hormone production. It becomes a self-reinforcing cycle.</p>
<h3>Blood sugar disruption</h3>
<p>A hypothyroid state slows glucose uptake by the cells and blunts insulin sensitivity, which can cause episodes of low blood sugar (hypoglycemia). The adrenals respond by releasing cortisol to stabilize blood sugar — and elevated cortisol further suppresses thyroid function. This blood sugar-thyroid-cortisol loop is one reason thyroid dysfunction is so often associated with PCOS-like symptoms and insulin resistance.</p>
<h2>How Hyperthyroidism Affects Your Cycle</h2>
<p>An overactive thyroid creates the opposite hormonal environment. Elevated thyroid hormones drive up SHBG, which binds more estrogen and testosterone — leaving less free hormone available for the body to use. Despite potentially elevated total hormone levels on a blood test, the biologically available fraction is reduced.</p>
<p>Hyperthyroidism also increases clotting factors, which tends to produce lighter, shorter bleeds. Women with overactive thyroids often experience <strong>light, infrequent, or absent periods</strong> — oligomenorrhea or amenorrhea — along with shorter cycle lengths. For a deeper dive into this pattern, see <a href="/articles/how-hyperthyroidism-affects-your-period">how hyperthyroidism affects your period</a>.</p>
<h2>Hashimoto's Thyroiditis: The Autoimmune Factor</h2>
<p>Hashimoto's thyroiditis is the most common cause of hypothyroidism in the developed world, yet it is routinely missed. Why? Because most conventional doctors only test TSH — and in early or mild Hashimoto's, TSH can still fall within the "normal" range even while the immune system is actively attacking thyroid tissue.</p>
<p>In Hashimoto's, the immune system mistakenly produces antibodies that target the thyroid's hormone-producing cells. This is not fundamentally a thyroid problem — it is an <strong>immune system problem</strong> that happens to express itself in the thyroid. The damage is often slow and gradual, which makes it difficult to catch until significant thyroid tissue has already been destroyed.</p>
<h3>The estrogen-Hashimoto's link</h3>
<p>Women are five to eight times more likely to develop thyroid disease than men, and the incidence peaks between puberty and menopause — a strong signal that sex hormones play a role. Estrogen has a direct proliferative effect on thyroid tissue, and estrogen dominance (elevated estrogen relative to progesterone) appears to be a meaningful driver of autoimmune thyroid activity.</p>
<p>One mechanism involves <strong>thyroid binding globulin (TBG)</strong>. Elevated estrogen raises TBG, which binds up more thyroid hormone and reduces the free fraction available to cells. This can produce hypothyroid symptoms even when the thyroid itself is producing adequate hormone. Oral contraceptives and hormone replacement therapy are significant drivers of this pattern, because they suppress ovulation and progesterone production while raising estrogen.</p>
<p>Progesterone, conversely, has a protective effect on the thyroid. It has a TSH-lowering effect and counteracts estrogen's overstimulation of thyroid tissue. This means that consistently low progesterone — whether from anovulatory cycles, chronic stress, or luteal phase dysfunction — removes a key protective layer for the thyroid. This is one more reason why <a href="/articles/low-progesterone-why-it-happens-and-what-you-can-do-about-it">supporting healthy progesterone</a> matters for the whole hormonal ecosystem.</p>
<h3>Gluten and molecular mimicry</h3>
<p>For women with Hashimoto's — or suspected autoimmune thyroid activity — gluten deserves serious attention. The protein structure of gliadin (the inflammatory component of gluten) closely resembles transglutaminase, an enzyme found in abundance in thyroid tissue. When gliadin enters the bloodstream — particularly in the context of intestinal permeability, or "leaky gut" — the immune system produces antibodies against it. Because of the structural similarity, those same antibodies can mistakenly attack thyroid tissue. This is called <strong>molecular mimicry</strong>.</p>
<p>Research has found that people with celiac disease are significantly more likely to have thyroid disease, and that a strict gluten-free diet can reduce thyroid antibodies and, in some cases, allow thyroid function to normalize. Even in the absence of a celiac diagnosis, non-celiac gluten sensitivity can drive the same antibody response. If you want a broader look at gluten and hormones, see <a href="/articles/is-gluten-bad">is gluten bad for your hormones</a>.</p>
<div class="article-cta-box">
<h3>Not sure if your thyroid could be affecting your cycle?</h3>
<p>The free Hormone Health Assessment maps your symptoms to potential root causes — including thyroid dysfunction, low progesterone, and estrogen imbalance. It takes five minutes and gives you a personalized starting point.</p>
<a class="btn btn-terra" href="https://fixyourperiod.app/quiz" target="_blank">Take the Free Assessment →</a>
</div>
<h2>The Problem with Standard TSH Testing</h2>
<p>Here is one of the most important things to understand about thyroid diagnosis: <strong>a "normal" TSH result does not mean your thyroid is functioning optimally.</strong></p>
<p>The conventional TSH reference range varies by laboratory but typically spans approximately <strong>0.45–5.0 mIU/L</strong>. This wide range was established using statistical averages of people who came in for testing — many of whom were already experiencing health problems. From a functional medicine perspective, this is the wrong baseline.</p>
<p>The <strong>optimal or functional TSH range</strong> is considerably narrower: <strong>0.5–2.0 mIU/L</strong>. A TSH of 4.0 would be considered completely normal by conventional standards, but from a functional perspective it signals that the thyroid is struggling and the pituitary is working overtime to compensate. Meanwhile, that woman may be experiencing fatigue, hair thinning, heavy periods, low mood, and fertility challenges — all dismissed because her labs are "within range."</p>
<p>This is not a rare situation. It is extraordinarily common, and it is a form of medical gaslighting that leaves millions of women without answers or appropriate care.</p>
<h3>What a full thyroid panel actually looks like</h3>
<p>Testing TSH alone — or even TSH plus total T4 — misses much of what can go wrong in thyroid physiology. A complete picture requires:</p>
<ul>
<li><strong>TSH</strong> — pituitary signal to the thyroid; optimal range 0.5–2.0 mIU/L</li>
<li><strong>Free T4</strong> — the inactive storage form; optimal range 1.0–1.5 ng/dL</li>
<li><strong>Free T3</strong> — the active form cells actually use; optimal range 2.5–4.0 pg/mL</li>
<li><strong>Reverse T3 (rT3)</strong> — the "brake" on metabolism; elevated when the body is under chronic stress or illness; optimal range 9–21 ng/dL</li>
<li><strong>TPO antibodies (thyroid peroxidase antibodies)</strong> — elevated in Hashimoto's; optimal below 15 IU/mL</li>
<li><strong>Thyroglobulin antibodies (TgAb)</strong> — second marker for Hashimoto's; optimal below 0.9 IU/mL</li>
</ul>
<p>Many women are told their thyroid is fine after only TSH is tested. If T3 (the active hormone) is not measured, a conversion problem in the liver or gut will go completely undetected. If antibodies are not tested, Hashimoto's will not be identified until significant tissue destruction has already occurred. Advocate for a full panel — or work with a functional medicine or naturopathic physician who will order one.</p>
<h2>What Disrupts Thyroid Function</h2>
<h3>Environmental toxins: fluoride, chlorine, and bromide</h3>
<p>The thyroid is uniquely vulnerable to a class of environmental chemicals that displace iodine — the raw material the thyroid uses to make hormone. Fluoride (in tap water and toothpaste), chlorine (in municipal water), and bromide (found in commercial baked goods and fire-retardant chemicals) are all halogens that compete with iodine for absorption into thyroid tissue. Regular exposure effectively crowds out iodine and impairs thyroid hormone production.</p>
<p>Additional environmental disruptors include persistent organic pollutants like PCBs and dioxins, as well as BPA and phthalates from plastics. These chemicals interfere with the HPT axis, reduce T4 output, and can block thyroid receptor function. Using a quality water filter, choosing glass and stainless steel over plastic, and buying organic where possible are meaningful first steps. Sweating regularly — through exercise, sauna, or both — supports the body's ability to excrete these toxins. For more on environmental impacts on hormonal health, see <a href="/articles/7-surprising-reasons-women-lose-their-hair">7 surprising reasons women lose their hair</a> (many of the same disruptors affect both).</p>
<h3>Chronic stress and cortisol</h3>
<p>Because the HPA and HPT axes share the hypothalamus and pituitary, chronic stress directly suppresses thyroid function. Elevated cortisol inhibits TSH production from the pituitary and suppresses the deiodinase enzyme that converts T4 to T3 in peripheral tissues. It also drives higher conversion of T4 into <strong>reverse T3</strong> — an inactive form of thyroid hormone that blocks T3 receptors and acts as a brake on metabolism. The result is all the symptoms of hypothyroidism even when standard labs look acceptable.</p>
<h3>Poor gut health</h3>
<p>The gut is one of the primary sites for T4-to-T3 conversion. Gut inflammation, dysbiosis, and intestinal permeability all impair this conversion, reduce the absorption of thyroid-critical nutrients, and generate inflammatory cytokines that damage hormone-converting cells. If your gut is compromised, your thyroid function is compromised — regardless of what your thyroid is doing on its own.</p>
<h3>Estrogen dominance</h3>
<p>As discussed above, excess estrogen relative to progesterone raises TBG, binds up thyroid hormone, and reduces the free fraction that cells can actually use. For women on hormonal birth control, or those with progesterone deficiency due to anovulatory cycles, this pattern is extremely common — and it means that period symptoms and thyroid symptoms are often appearing at the same time for the same underlying reason.</p>
<h2>Nutrients Critical for Thyroid Function</h2>
<p>The thyroid is one of the most nutritionally demanding glands in the body. Deficiencies in any of the following can impair hormone production, conversion, or receptor sensitivity:</p>
<ul>
<li><strong>Iodine</strong> — the primary raw material for thyroid hormone; found in sea vegetables, ocean fish, eggs, and dairy. The recommended intake is 150 mcg per day. Iodine deficiency is the most common cause of hypothyroidism worldwide. Note: supplemental iodine should only be taken under practitioner guidance, as excess can worsen Hashimoto's, particularly in the presence of selenium deficiency.</li>
<li><strong>Selenium</strong> — essential for T4-to-T3 conversion and for protecting the thyroid from oxidative damage; also helps keep thyroid antibodies in check. Brazil nuts (a few daily), seafood, and organ meats are excellent sources. Supplemental dose: up to 200 mcg of selenomethionine per day.</li>
<li><strong>Zinc</strong> — critical for T4-to-T3 conversion and thyroid receptor function. Found in beef, shellfish, and pumpkin seeds. Supplemental dose: 15–30 mg of zinc picolinate or zinc bisglycinate daily, taken with food.</li>
<li><strong>Iron</strong> — required for thyroid peroxidase, the enzyme that synthesizes thyroid hormone. Iron deficiency is extremely common in women with heavy periods and directly impairs thyroid output. Best sourced from heme iron in red meat and liver; iron bisglycinate is better tolerated as a supplement than ferrous sulfate.</li>
<li><strong>Vitamin D</strong> — low vitamin D is consistently associated with Hashimoto's and Graves' disease. Test your levels; most people need to supplement. Vitamin D works synergistically with magnesium and vitamin K2, so deficiencies in those minerals should be addressed too. See <a href="/articles/vitamin-d-the-period-vitamin">vitamin D: the period vitamin</a> for more detail.</li>
<li><strong>Magnesium</strong> — supports T4 production and T4-to-T3 conversion; deficiency is linked to elevated thyroid antibodies, goiter, and Hashimoto's. Magnesium glycinate or malate are well-absorbed forms. For more on magnesium's broader hormonal role, see <a href="/articles/the-many-benefits-of-magnesium-for-your-health-cycle">the many benefits of magnesium for your health and cycle</a>.</li>
<li><strong>Vitamin B12</strong> — commonly deficient in hypothyroidism, particularly Hashimoto's; supports energy production and neurological function. Found in animal foods; methylcobalamin is the preferred supplemental form.</li>
</ul>
<h2>Natural Support Strategies — and When Medication Is Needed</h2>
<p>If your full thyroid panel reveals that your levels are trending out of optimal range — even if still within conventional "normal" — the foundational steps below can make a meaningful difference over several months:</p>
<ul>
<li><strong>Stabilize blood sugar</strong> — blood sugar dysregulation is a core driver of thyroid suppression and cortisol elevation. Eating protein and fat at every meal, avoiding long gaps between eating, and limiting refined carbohydrates are non-negotiable starting points.</li>
<li><strong>Reduce inflammatory foods</strong> — particularly gluten (especially for Hashimoto's) and highly processed soy, which inhibits thyroid peroxidase. Cooked cruciferous vegetables are fine; raw in large quantities may be best limited if iodine status is low.</li>
<li><strong>Support gut health</strong> — address dysbiosis, intestinal permeability, and chronic gut inflammation through fermented foods, bone broth, targeted probiotics, and if needed, functional gut testing.</li>
<li><strong>Reduce toxin exposure</strong> — filter drinking water (a quality carbon or reverse osmosis filter will remove fluoride, chlorine, and heavy metals), choose glass or stainless steel for food and water storage, and reduce synthetic personal care and cleaning products.</li>
<li><strong>Address estrogen clearance</strong> — support liver detoxification through cruciferous vegetables, adequate fiber, and limiting alcohol. If estrogen dominance is a driver, supporting progesterone naturally through the strategies in <a href="/articles/low-progesterone-why-it-happens-and-what-you-can-do-about-it">this low progesterone guide</a> will also benefit the thyroid.</li>
<li><strong>Prioritize sleep and stress management</strong> — cortisol suppression of thyroid function is real and direct. Sleep, nervous system regulation, and addressing the sources of chronic stress are not optional extras.</li>
<li><strong>Consider ashwagandha</strong> — this adaptogenic herb has clinical evidence for increasing T3 and T4 levels, lowering TSH, and supporting both HPA and HPT axis function. Studies used 300–600 mg per day of a standardized extract.</li>
</ul>
<p>These strategies work best for subclinical hypothyroidism and early-stage Hashimoto's. If thyroid levels are significantly out of range — particularly free T3 and free T4 — or if symptoms are severe and impacting quality of life, thyroid medication is often appropriate and necessary. Levothyroxine (synthetic T4) is the most commonly prescribed option, but some women do better on combination T4/T3 preparations like desiccated thyroid hormone. The key is not to see medication as a last resort, but to use it as part of a comprehensive strategy that still addresses root causes — otherwise the underlying dysfunction continues even while the numbers normalize.</p>
<p>Work with a functional medicine physician, integrative doctor, or naturopath who will run a full panel, interpret results against optimal ranges, and partner with you on both lifestyle interventions and medication if needed. Your body is telling you something. The numbers are just one part of the story.</p>
`

export default function ArticleBody() {
  // eslint-disable-next-line react/no-danger
  return <div dangerouslySetInnerHTML={{ __html: html }} />
}
