name: Deploy to Production

on:
  push:
    branches:
      - nextjs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Vercel production deployment
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "nj-website",
              "gitSource": {
                "type": "github",
                "repoId": 1198948168,
                "ref": "nextjs"
              },
              "target": "production"
            }' \
            "https://api.vercel.com/v13/deployments?teamId=team_Otn5h1teztjgsFakaVmZlLIg&forceNew=1"
